[ 2022-05-02T12:00:49     INFO ] logging to applications insights
[ 2022-05-02T12:00:50     INFO ] [ exists                   ] True
[ 2022-05-02T12:00:51     INFO ] [ get                      ] {'additional_properties': {}, 'id': '/subscriptions/b698965a-1f53-45ec-8b81-58458d1b25f7/resourceGroups/VMSSReImageRun1SOUTHCENTRALUS', 'name': 'VMSSReImageRun1SOUTHCENTRALUS', 'type': 'Microsoft.Resources/resourceGroups', 'properties': <azure.mgmt.resource.resources.v2021_04_01.models._models_py3.ResourceGroupProperties object at 0x7f77017a1d30>, 'location': 'southcentralus', 'managed_by': None, 'tags': None}
[ 2022-05-02T12:00:58     INFO ] [ create                   ] {'additional_properties': {}, 'id': '/subscriptions/b698965a-1f53-45ec-8b81-58458d1b25f7/resourceGroups/VMSSReImageRun1SOUTHCENTRALUS/providers/Microsoft.Storage/storageAccounts/vmsspipeline9fc2a6bc', 'name': 'vmsspipeline9fc2a6bc', 'type': 'Microsoft.Storage/storageAccounts', 'tags': {'confidentiality': 'public'}, 'location': 'southcentralus', 'sku': <azure.mgmt.storage.v2021_09_01.models._models_py3.Sku object at 0x7f77015e14c0>, 'kind': 'StorageV2', 'identity': None, 'extended_location': None, 'provisioning_state': 'Succeeded', 'primary_endpoints': <azure.mgmt.storage.v2021_09_01.models._models_py3.Endpoints object at 0x7f77015e1a60>, 'primary_location': 'southcentralus', 'status_of_primary': 'available', 'last_geo_failover_time': None, 'secondary_location': None, 'status_of_secondary': None, 'creation_time': datetime.datetime(2022, 4, 29, 16, 7, 7, 364576, tzinfo=<isodate.tzinfo.Utc object at 0x7f77052e8e20>), 'custom_domain': None, 'sas_policy': None, 'key_policy': None, 'key_creation_time': <azure.mgmt.storage.v2021_09_01.models._models_py3.KeyCreationTime object at 0x7f77015e1c70>, 'secondary_endpoints': None, 'encryption': <azure.mgmt.storage.v2021_09_01.models._models_py3.Encryption object at 0x7f77015e1af0>, 'access_tier': 'Hot', 'azure_files_identity_based_authentication': None, 'enable_https_traffic_only': True, 'network_rule_set': <azure.mgmt.storage.v2021_09_01.models._models_py3.NetworkRuleSet object at 0x7f77015e1d90>, 'is_sftp_enabled': None, 'is_local_user_enabled': None, 'is_hns_enabled': None, 'geo_replication_stats': None, 'failover_in_progress': None, 'large_file_shares_state': None, 'private_endpoint_connections': [], 'routing_preference': None, 'blob_restore_status': None, 'allow_blob_public_access': True, 'minimum_tls_version': 'TLS1_0', 'allow_shared_key_access': None, 'enable_nfs_v3': None, 'allow_cross_tenant_replication': None, 'default_to_o_auth_authentication': None, 'public_network_access': None, 'immutable_storage_with_versioning': None, 'allowed_copy_scope': None, 'storage_account_sku_conversion_status': None, 'dns_endpoint_type': None}
[ 2022-05-02T12:00:59     INFO ] [ get                      ] {'additional_properties': {}, 'id': '/subscriptions/b698965a-1f53-45ec-8b81-58458d1b25f7/resourceGroups/VMSSReImageRun1SOUTHCENTRALUS/providers/Microsoft.Network/networkSecurityGroups/vmssPeregrineTest-nsg', 'name': 'vmssPeregrineTest-nsg', 'type': 'Microsoft.Network/networkSecurityGroups', 'location': 'southcentralus', 'tags': {'confidentiality': 'public'}, 'etag': 'W/"eb7d1979-ed01-4960-a05c-263594cf31d5"', 'security_rules': [<azure.mgmt.network.v2021_05_01.models._models_py3.SecurityRule object at 0x7f7700f24730>], 'default_security_rules': [<azure.mgmt.network.v2021_05_01.models._models_py3.SecurityRule object at 0x7f7700f24cd0>, <azure.mgmt.network.v2021_05_01.models._models_py3.SecurityRule object at 0x7f7700f24c40>, <azure.mgmt.network.v2021_05_01.models._models_py3.SecurityRule object at 0x7f7700f24760>, <azure.mgmt.network.v2021_05_01.models._models_py3.SecurityRule object at 0x7f7700f248b0>, <azure.mgmt.network.v2021_05_01.models._models_py3.SecurityRule object at 0x7f7700f249d0>, <azure.mgmt.network.v2021_05_01.models._models_py3.SecurityRule object at 0x7f7700f24c70>], 'network_interfaces': None, 'subnets': [<azure.mgmt.network.v2021_05_01.models._models_py3.Subnet object at 0x7f7700f24be0>], 'flow_logs': None, 'resource_guid': 'a66db6d6-770c-4f59-9ac2-c283de4a9a24', 'provisioning_state': 'Succeeded'}
[ 2022-05-02T12:01:00     INFO ] [ get                      ] {'additional_properties': {}, 'id': '/subscriptions/b698965a-1f53-45ec-8b81-58458d1b25f7/resourceGroups/VMSSReImageRun1SOUTHCENTRALUS/providers/Microsoft.Network/virtualNetworks/vmssPeregrineTest-vnet', 'name': 'vmssPeregrineTest-vnet', 'type': 'Microsoft.Network/virtualNetworks', 'location': 'southcentralus', 'tags': {'confidentiality': 'public'}, 'extended_location': None, 'etag': 'W/"d5b4eb7c-ea37-462b-9ea4-fbd232834c2c"', 'address_space': <azure.mgmt.network.v2021_05_01.models._models_py3.AddressSpace object at 0x7f7700f248e0>, 'dhcp_options': None, 'flow_timeout_in_minutes': None, 'subnets': [<azure.mgmt.network.v2021_05_01.models._models_py3.Subnet object at 0x7f7700f246a0>], 'virtual_network_peerings': [], 'resource_guid': '0f1294d0-ba81-42f8-bd75-de499de66b2f', 'provisioning_state': 'Succeeded', 'enable_ddos_protection': False, 'enable_vm_protection': None, 'ddos_protection_plan': None, 'bgp_communities': None, 'encryption': None, 'ip_allocations': None}
[ 2022-05-02T12:01:00     INFO ] [ subnets_list             ] <iterator object azure.core.paging.ItemPaged at 0x7f7700f24dc0>
[ 2022-05-02T12:01:02     INFO ] [ get                      ] {'additional_properties': {}, 'id': '/subscriptions/b698965a-1f53-45ec-8b81-58458d1b25f7/resourceGroups/VMSSReImageRun1SOUTHCENTRALUS/providers/Microsoft.Compute/virtualMachineScaleSets/vmssPeregrineTest', 'name': 'vmssPeregrineTest', 'type': 'Microsoft.Compute/virtualMachineScaleSets', 'location': 'southcentralus', 'tags': {'confidentiality': 'public'}, 'sku': <azure.mgmt.compute.v2021_11_01.models._models_py3.Sku object at 0x7f7700c99790>, 'plan': None, 'identity': None, 'zones': ['1'], 'extended_location': None, 'upgrade_policy': None, 'automatic_repairs_policy': None, 'virtual_machine_profile': <azure.mgmt.compute.v2021_11_01.models._models_py3.VirtualMachineScaleSetVMProfile object at 0x7f7700c99ca0>, 'provisioning_state': 'Succeeded', 'overprovision': None, 'do_not_run_extensions_on_overprovisioned_v_ms': None, 'unique_id': '37746c0b-92b4-4b45-961f-474922163bb5', 'single_placement_group': False, 'zone_balance': None, 'platform_fault_domain_count': 1, 'proximity_placement_group': None, 'host_group': None, 'additional_capabilities': None, 'scale_in_policy': None, 'orchestration_mode': 'Flexible', 'spot_restore_policy': None, 'time_created': datetime.datetime(2022, 4, 29, 16, 7, 45, 135353, tzinfo=<FixedOffset '+00:00'>)}
[ 2022-05-02T12:01:02     INFO ] [ get_vms                  ] <iterator object azure.core.paging.ItemPaged at 0x7f7700f5b190>
[ 2022-05-02T12:01:02    DEBUG ] Using selector: EpollSelector
[ 2022-05-02T12:01:02     INFO ] [ get_vms                  ] <iterator object azure.core.paging.ItemPaged at 0x7f7700c29a00>
[ 2022-05-02T12:01:03     INFO ] Finish queuing all vms
[ 2022-05-02T12:01:03     INFO ] [ get                      ] {'additional_properties': {}, 'platform_update_domain': None, 'platform_fault_domain': None, 'computer_name': 'vmInstance1OE4NY', 'os_name': 'ubuntu', 'os_version': '18.04', 'hyper_v_generation': 'V1', 'rdp_thumb_print': None, 'vm_agent': <azure.mgmt.compute.v2021_11_01.models._models_py3.VirtualMachineAgentInstanceView object at 0x7f7700c55d30>, 'maintenance_redeploy_status': None, 'disks': [<azure.mgmt.compute.v2021_11_01.models._models_py3.DiskInstanceView object at 0x7f7700c55f10>], 'extensions': [], 'vm_health': None, 'boot_diagnostics': <azure.mgmt.compute.v2021_11_01.models._models_py3.BootDiagnosticsInstanceView object at 0x7f7700c55dc0>, 'assigned_host': None, 'statuses': [<azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f7700c590a0>, <azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f7700c590d0>], 'patch_status': None}
[ 2022-05-02T12:01:04     INFO ] [ get                      ] {'additional_properties': {}, 'platform_update_domain': None, 'platform_fault_domain': None, 'computer_name': 'vmInstance1ZB63N', 'os_name': 'ubuntu', 'os_version': '18.04', 'hyper_v_generation': 'V1', 'rdp_thumb_print': None, 'vm_agent': <azure.mgmt.compute.v2021_11_01.models._models_py3.VirtualMachineAgentInstanceView object at 0x7f76f3e210a0>, 'maintenance_redeploy_status': None, 'disks': [<azure.mgmt.compute.v2021_11_01.models._models_py3.DiskInstanceView object at 0x7f76f3e21280>], 'extensions': [], 'vm_health': None, 'boot_diagnostics': <azure.mgmt.compute.v2021_11_01.models._models_py3.BootDiagnosticsInstanceView object at 0x7f76f3e21130>, 'assigned_host': None, 'statuses': [<azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f76f3e213d0>, <azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f76f3e21400>], 'patch_status': None}
[ 2022-05-02T12:01:05     INFO ] [ get                      ] {'additional_properties': {}, 'platform_update_domain': None, 'platform_fault_domain': None, 'computer_name': 'vmInstance2C0PSP', 'os_name': 'ubuntu', 'os_version': '18.04', 'hyper_v_generation': 'V1', 'rdp_thumb_print': None, 'vm_agent': <azure.mgmt.compute.v2021_11_01.models._models_py3.VirtualMachineAgentInstanceView object at 0x7f76f3e284c0>, 'maintenance_redeploy_status': None, 'disks': [<azure.mgmt.compute.v2021_11_01.models._models_py3.DiskInstanceView object at 0x7f76f3e286a0>], 'extensions': [], 'vm_health': None, 'boot_diagnostics': <azure.mgmt.compute.v2021_11_01.models._models_py3.BootDiagnosticsInstanceView object at 0x7f76f3e28550>, 'assigned_host': None, 'statuses': [<azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f76f3e287f0>, <azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f76f3e28820>], 'patch_status': None}
[ 2022-05-02T12:01:06  WARNING ] AzureCliCredential.get_token failed: Unexpected output from Azure CLI: '--- Logging error ---
Traceback (most recent call last):
  File "/home/crodriguezde/.local/lib/python3.8/site-packages/azure/cli/__main__.py", line 60, in <module>
    raise ex
  File "/home/crodriguezde/.local/lib/python3.8/site-packages/azure/cli/__main__.py", line 53, in <module>
    sys.exit(exit_code)
SystemExit: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/handlers.py", line 70, in emit
    self.doRollover()
  File "/usr/lib/python3.8/logging/handlers.py", line 167, in doRollover
    os.rename(sfn, dfn)
FileNotFoundError: [Errno 2] No such file or directory: '/home/crodriguezde/.azure/telemetry/cache.3' -> '/home/crodriguezde/.azure/telemetry/cache.4'
Call stack:
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/crodriguezde/.local/lib/python3.8/site-packages/azure/cli/__main__.py", line 123, in <module>
    telemetry.conclude()
  File "/home/crodriguezde/.local/lib/python3.8/site-packages/azure/cli/core/telemetry.py", line 241, in _wrapper
    return func(*args, **kwargs)
  File "/home/crodriguezde/.local/lib/python3.8/site-packages/azure/cli/core/decorators.py", line 79, in _wrapped_func
    return func(*args, **kwargs)
  File "/home/crodriguezde/.local/lib/python3.8/site-packages/azure/cli/core/telemetry.py", line 297, in conclude
    save(get_config_dir(), _session.generate_payload())
  File "/home/crodriguezde/.local/lib/python3.8/site-packages/azure/cli/telemetry/__init__.py", line 51, in save
    if save_payload(config_dir, payload) and should_upload(config_dir):
  File "/home/crodriguezde/.local/lib/python3.8/site-packages/azure/cli/telemetry/util.py", line 53, in save_payload
    cache_saver.info(payload)
Message: '{"c4395b75-49cc-422c-bc95-c7d51aef5d46":[{"name":"azurecli/command","properties":{"Reserved.DataModel.EntityType":"UserTask","Reserved.DataModel.Action.Type":"Atomic","Reserved.DataModel.Action.Result":"Success","Reserved.ChannelUsed":"AI","Reserved.EventId":"7bb75fb2-7f38-4325-8967-726df5fd0518","Reserved.SequenceNumber":1,"Reserved.SessionId":"84d6105baf4e29c6e27aeb757dda4d55c4a5682eacb4f88180ddceb55756f3fa","Reserved.TimeSinceSessionStart":0,"Reserved.DataModel.Source":"DataModelAPI","Reserved.DataModel.EntitySchemaVersion":4,"Reserved.DataModel.Severity":0,"Reserved.DataModel.ProductName":"azurecli","Reserved.DataModel.FeatureName":"command","Reserved.DataModel.EntityName":"account-getaccesstoken","Reserved.DataModel.CorrelationId":"d841e863-94cb-4d28-8fc6-fd69b89d4a66","Context.Default.VS.Core.ExeName":"azurecli","Context.Default.VS.Core.ExeVersion":"2.36.0@none","Context.Default.VS.Core.MacAddressHash":"e9bfd1348393ff8f258c5b795e82bf541f4459c5b4d6fa911e34d480ac33d348","Context.Default.VS.Core.Machine.Id":"e9bfd134-8393-ff8f-258c-5b795e82bf54","Context.Default.VS.Core.OS.Type":"linux","Context.Default.VS.Core.OS.Version":"#1 smp wed mar 2 00:30:59 utc 2022","Context.Default.VS.Core.OS.Platform":"linux-5.10.102.1-microsoft-standard-wsl2-x86_64-with-glibc2.29","Context.Default.VS.Core.User.Id":"64c5b0af-e344-11eb-b316-c03c59895c0a","Context.Default.VS.Core.User.IsMicrosoftInternal":"False","Context.Default.VS.Core.User.IsOptedIn":"True","Context.Default.VS.Core.TelemetryApi.ProductVersion":"azurecli@2.36.0","Context.Default.AzureCLI.Source":"az","Context.Default.AzureCLI.ClientRequestId":"74898468-ca39-11ec-9f7e-00155d785913","Context.Default.AzureCLI.CoreVersion":"2.36.0","Context.Default.AzureCLI.TelemetryVersion":"2.0","Context.Default.AzureCLI.InstallationId":"64c5b0af-e344-11eb-b316-c03c59895c0a","Context.Default.AzureCLI.ShellType":"/usr/bin/zsh","Context.Default.AzureCLI.UserAzureId":"39921e2f44771b3d76a90cf4cac837fdf8e646729bbbcbe017a174f2298b5c4c","Context.Default.AzureCLI.UserAzureSubscriptionId":"b698965a-1f53-45ec-8b81-58458d1b25f7","Context.Default.AzureCLI.DefaultOutputType":"unknown","Context.Default.AzureCLI.EnvironmentVariables":"[]","Context.Default.AzureCLI.Locale":"en_US,UTF-8","Context.Default.AzureCLI.StartTime":"2022-05-02 17:01:05.860261","Context.Default.AzureCLI.EndTime":"2022-05-02 17:01:06.124071","Context.Default.AzureCLI.InitTimeElapsed":"0.135410","Context.Default.AzureCLI.InvokeTimeElapsed":"0.260367","Context.Default.AzureCLI.OutputType":"json","Context.Default.AzureCLI.RawCommand":"account get-access-token","Context.Default.AzureCLI.Params":"--output,--resource","Context.Default.AzureCLI.PythonVersion":"3.8.10","Context.Default.AzureCLI.Mode":"default","Context.Default.AzureCLI.Installer":"PIP","Context.Default.AzureCLI.error_type":"None","Context.Default.AzureCLI.exception_name":"None","Context.Default.AzureCLI.debug_info":"","Context.Default.AzureCLI.PollStartTime":"None","Context.Default.AzureCLI.PollEndTime":"None"}}]}'
Arguments: ()
{
  ****,
  "expiresOn": "2022-05-02 12:54:18.000000",
  "subscription": "b698965a-1f53-45ec-8b81-58458d1b25f7",
  "tenant": "72f988bf-86f1-41af-91ab-2d7cd011db47",
  "tokenType": "Bearer"
}
'. 
To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/python/identity/azclicredential/troubleshoot.
[ 2022-05-02T12:01:07     INFO ] [ get                      ] {'additional_properties': {}, 'platform_update_domain': None, 'platform_fault_domain': None, 'computer_name': 'vmInstance2RNIEP', 'os_name': 'ubuntu', 'os_version': '18.04', 'hyper_v_generation': 'V1', 'rdp_thumb_print': None, 'vm_agent': <azure.mgmt.compute.v2021_11_01.models._models_py3.VirtualMachineAgentInstanceView object at 0x7f76f3e337c0>, 'maintenance_redeploy_status': None, 'disks': [<azure.mgmt.compute.v2021_11_01.models._models_py3.DiskInstanceView object at 0x7f76f3e339a0>], 'extensions': [], 'vm_health': None, 'boot_diagnostics': <azure.mgmt.compute.v2021_11_01.models._models_py3.BootDiagnosticsInstanceView object at 0x7f76f3e33760>, 'assigned_host': None, 'statuses': [<azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f76f3e33b20>, <azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f76f3e33b50>], 'patch_status': None}
[ 2022-05-02T12:01:08     INFO ] [ get                      ] {'additional_properties': {}, 'platform_update_domain': None, 'platform_fault_domain': None, 'computer_name': 'vmInstance2UT10B', 'os_name': 'ubuntu', 'os_version': '18.04', 'hyper_v_generation': 'V1', 'rdp_thumb_print': None, 'vm_agent': <azure.mgmt.compute.v2021_11_01.models._models_py3.VirtualMachineAgentInstanceView object at 0x7f76f35bfc40>, 'maintenance_redeploy_status': None, 'disks': [<azure.mgmt.compute.v2021_11_01.models._models_py3.DiskInstanceView object at 0x7f76f35bfe20>], 'extensions': [], 'vm_health': None, 'boot_diagnostics': <azure.mgmt.compute.v2021_11_01.models._models_py3.BootDiagnosticsInstanceView object at 0x7f76f35bfcd0>, 'assigned_host': None, 'statuses': [<azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f76f35bff70>, <azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f76f35bffa0>], 'patch_status': None}
[ 2022-05-02T12:01:09     INFO ] [ get                      ] {'additional_properties': {}, 'platform_update_domain': None, 'platform_fault_domain': None, 'computer_name': 'vmInstance3BVHI3', 'os_name': 'ubuntu', 'os_version': '18.04', 'hyper_v_generation': 'V1', 'rdp_thumb_print': None, 'vm_agent': <azure.mgmt.compute.v2021_11_01.models._models_py3.VirtualMachineAgentInstanceView object at 0x7f76f35d0220>, 'maintenance_redeploy_status': None, 'disks': [<azure.mgmt.compute.v2021_11_01.models._models_py3.DiskInstanceView object at 0x7f76f35d0400>], 'extensions': [], 'vm_health': None, 'boot_diagnostics': <azure.mgmt.compute.v2021_11_01.models._models_py3.BootDiagnosticsInstanceView object at 0x7f76f35d02b0>, 'assigned_host': None, 'statuses': [<azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f76f35d0550>, <azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f76f35d0580>], 'patch_status': None}
[ 2022-05-02T12:01:10     INFO ] [ get                      ] {'additional_properties': {}, 'platform_update_domain': None, 'platform_fault_domain': None, 'computer_name': 'vmInstance3NM16Y', 'os_name': 'ubuntu', 'os_version': '18.04', 'hyper_v_generation': 'V1', 'rdp_thumb_print': None, 'vm_agent': <azure.mgmt.compute.v2021_11_01.models._models_py3.VirtualMachineAgentInstanceView object at 0x7f76f35d7640>, 'maintenance_redeploy_status': None, 'disks': [<azure.mgmt.compute.v2021_11_01.models._models_py3.DiskInstanceView object at 0x7f76f35d7820>], 'extensions': [], 'vm_health': None, 'boot_diagnostics': <azure.mgmt.compute.v2021_11_01.models._models_py3.BootDiagnosticsInstanceView object at 0x7f76f35d76d0>, 'assigned_host': None, 'statuses': [<azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f76f35d7970>, <azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f76f35d79a0>], 'patch_status': None}
[ 2022-05-02T12:01:11     INFO ] [ get                      ] {'additional_properties': {}, 'platform_update_domain': None, 'platform_fault_domain': None, 'computer_name': 'vmInstance46BHVP', 'os_name': 'ubuntu', 'os_version': '18.04', 'hyper_v_generation': 'V1', 'rdp_thumb_print': None, 'vm_agent': <azure.mgmt.compute.v2021_11_01.models._models_py3.VirtualMachineAgentInstanceView object at 0x7f76f35dcbe0>, 'maintenance_redeploy_status': None, 'disks': [<azure.mgmt.compute.v2021_11_01.models._models_py3.DiskInstanceView object at 0x7f76f35dcdc0>], 'extensions': [], 'vm_health': None, 'boot_diagnostics': <azure.mgmt.compute.v2021_11_01.models._models_py3.BootDiagnosticsInstanceView object at 0x7f76f35dcc70>, 'assigned_host': None, 'statuses': [<azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f76f35dcf10>, <azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f76f35dcf40>], 'patch_status': None}
[ 2022-05-02T12:01:11     INFO ] [ get                      ] {'additional_properties': {}, 'platform_update_domain': None, 'platform_fault_domain': None, 'computer_name': 'vmInstance4MZ3H7', 'os_name': 'ubuntu', 'os_version': '18.04', 'hyper_v_generation': 'V1', 'rdp_thumb_print': None, 'vm_agent': <azure.mgmt.compute.v2021_11_01.models._models_py3.VirtualMachineAgentInstanceView object at 0x7f76f35eb1c0>, 'maintenance_redeploy_status': None, 'disks': [<azure.mgmt.compute.v2021_11_01.models._models_py3.DiskInstanceView object at 0x7f76f35eb3a0>], 'extensions': [], 'vm_health': None, 'boot_diagnostics': <azure.mgmt.compute.v2021_11_01.models._models_py3.BootDiagnosticsInstanceView object at 0x7f76f35eb250>, 'assigned_host': None, 'statuses': [<azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f76f35eb4f0>, <azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f76f35eb520>], 'patch_status': None}
[ 2022-05-02T12:01:12     INFO ] [ get                      ] {'additional_properties': {}, 'platform_update_domain': None, 'platform_fault_domain': None, 'computer_name': 'vmInstance4TUB0I', 'os_name': 'ubuntu', 'os_version': '18.04', 'hyper_v_generation': 'V1', 'rdp_thumb_print': None, 'vm_agent': <azure.mgmt.compute.v2021_11_01.models._models_py3.VirtualMachineAgentInstanceView object at 0x7f76f35f34c0>, 'maintenance_redeploy_status': None, 'disks': [<azure.mgmt.compute.v2021_11_01.models._models_py3.DiskInstanceView object at 0x7f76f35f36a0>], 'extensions': [], 'vm_health': None, 'boot_diagnostics': <azure.mgmt.compute.v2021_11_01.models._models_py3.BootDiagnosticsInstanceView object at 0x7f76f35f3550>, 'assigned_host': None, 'statuses': [<azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f76f35f37f0>, <azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f76f35f3820>], 'patch_status': None}
[ 2022-05-02T12:01:13    DEBUG ] Encoding detection on empty bytes, assuming utf_8 intention.
[ 2022-05-02T12:01:13    DEBUG ] Encoding detection on empty bytes, assuming utf_8 intention.
[ 2022-05-02T12:01:13    DEBUG ] Encoding detection on empty bytes, assuming utf_8 intention.
[ 2022-05-02T12:01:13    DEBUG ] Encoding detection on empty bytes, assuming utf_8 intention.
[ 2022-05-02T12:01:13    DEBUG ] Encoding detection on empty bytes, assuming utf_8 intention.
[ 2022-05-02T12:01:13    DEBUG ] Encoding detection on empty bytes, assuming utf_8 intention.
[ 2022-05-02T12:01:13    DEBUG ] Encoding detection on empty bytes, assuming utf_8 intention.
[ 2022-05-02T12:01:13    DEBUG ] Encoding detection on empty bytes, assuming utf_8 intention.
[ 2022-05-02T12:01:13    DEBUG ] Encoding detection on empty bytes, assuming utf_8 intention.
[ 2022-05-02T12:01:13    DEBUG ] Encoding detection on empty bytes, assuming utf_8 intention.
[ 2022-05-02T12:01:33     INFO ] VMs in vm_queue:90
[ 2022-05-02T12:01:33     INFO ] VMs finish:0
[ 2022-05-02T12:01:44     INFO ] [ get                      ] {'additional_properties': {}, 'platform_update_domain': None, 'platform_fault_domain': None, 'computer_name': 'vmInstance6J1CJ8', 'os_name': 'ubuntu', 'os_version': '18.04', 'hyper_v_generation': 'V1', 'rdp_thumb_print': None, 'vm_agent': <azure.mgmt.compute.v2021_11_01.models._models_py3.VirtualMachineAgentInstanceView object at 0x7f76f04fcee0>, 'maintenance_redeploy_status': None, 'disks': [<azure.mgmt.compute.v2021_11_01.models._models_py3.DiskInstanceView object at 0x7f76f0505100>], 'extensions': [], 'vm_health': None, 'boot_diagnostics': <azure.mgmt.compute.v2021_11_01.models._models_py3.BootDiagnosticsInstanceView object at 0x7f76f04fcf70>, 'assigned_host': None, 'statuses': [<azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f76f0505250>, <azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f76f0505280>], 'patch_status': None}
[ 2022-05-02T12:01:45     INFO ] [ get                      ] {'additional_properties': {}, 'platform_update_domain': None, 'platform_fault_domain': None, 'computer_name': 'vmInstance7LN82P', 'os_name': 'ubuntu', 'os_version': '18.04', 'hyper_v_generation': 'V1', 'rdp_thumb_print': None, 'vm_agent': <azure.mgmt.compute.v2021_11_01.models._models_py3.VirtualMachineAgentInstanceView object at 0x7f76f05408e0>, 'maintenance_redeploy_status': None, 'disks': [<azure.mgmt.compute.v2021_11_01.models._models_py3.DiskInstanceView object at 0x7f76f0540fd0>], 'extensions': [], 'vm_health': None, 'boot_diagnostics': <azure.mgmt.compute.v2021_11_01.models._models_py3.BootDiagnosticsInstanceView object at 0x7f76f0540ee0>, 'assigned_host': None, 'statuses': [<azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f76f3e289d0>, <azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f76f3e288e0>], 'patch_status': None}
[ 2022-05-02T12:01:46     INFO ] [ get                      ] {'additional_properties': {}, 'platform_update_domain': None, 'platform_fault_domain': None, 'computer_name': 'vmInstance7T6J4T', 'os_name': 'ubuntu', 'os_version': '18.04', 'hyper_v_generation': 'V1', 'rdp_thumb_print': None, 'vm_agent': <azure.mgmt.compute.v2021_11_01.models._models_py3.VirtualMachineAgentInstanceView object at 0x7f76f3e28040>, 'maintenance_redeploy_status': None, 'disks': [<azure.mgmt.compute.v2021_11_01.models._models_py3.DiskInstanceView object at 0x7f76f3e281f0>], 'extensions': [], 'vm_health': None, 'boot_diagnostics': <azure.mgmt.compute.v2021_11_01.models._models_py3.BootDiagnosticsInstanceView object at 0x7f76f3e28ac0>, 'assigned_host': None, 'statuses': [<azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f76f3e28d00>, <azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f76f3e28a90>], 'patch_status': None}
[ 2022-05-02T12:01:46     INFO ] [ get                      ] {'additional_properties': {}, 'platform_update_domain': None, 'platform_fault_domain': None, 'computer_name': 'vmInstance8OF109', 'os_name': 'ubuntu', 'os_version': '18.04', 'hyper_v_generation': 'V1', 'rdp_thumb_print': None, 'vm_agent': <azure.mgmt.compute.v2021_11_01.models._models_py3.VirtualMachineAgentInstanceView object at 0x7f76f050bc40>, 'maintenance_redeploy_status': None, 'disks': [<azure.mgmt.compute.v2021_11_01.models._models_py3.DiskInstanceView object at 0x7f76f050be20>], 'extensions': [], 'vm_health': None, 'boot_diagnostics': <azure.mgmt.compute.v2021_11_01.models._models_py3.BootDiagnosticsInstanceView object at 0x7f76f050bcd0>, 'assigned_host': None, 'statuses': [<azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f76f050bf70>, <azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f76f050bfa0>], 'patch_status': None}
[ 2022-05-02T12:01:47    ERROR ] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f76f3e16220>
[ 2022-05-02T12:01:47    ERROR ] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f76f35cc100>
[ 2022-05-02T12:01:47    ERROR ] Task exception was never retrieved
future: <Task finished name='Task-2' coro=<logging_worker() done, defined at /home/crodriguezde/experiments/reimage/imds.py:40> exception=AttributeError("'dict' object has no attribute 'platformFaultDomain'")>
Traceback (most recent call last):
  File "/home/crodriguezde/experiments/reimage/imds.py", line 43, in logging_worker
    logger_retry(msg)
  File "/home/crodriguezde/experiments/reimage/venv/lib/python3.8/site-packages/backoff/_sync.py", line 94, in retry
    ret = target(*args, **kwargs)
  File "/home/crodriguezde/experiments/reimage/imds.py", line 37, in logger_retry
    utils.log_obj(msg)
  File "/home/crodriguezde/experiments/reimage/utils.py", line 26, in log_obj
    'platformFaultDomain': imds.platformFaultDomain,
AttributeError: 'dict' object has no attribute 'platformFaultDomain'
[ 2022-05-02T12:01:47    ERROR ] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f76f35e6070>
[ 2022-05-02T12:01:47    ERROR ] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f76f35f31f0>
[ 2022-05-02T12:01:47    ERROR ] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f76f35f31c0>
[ 2022-05-02T12:01:47     INFO ] Exit per user request
[ 2022-05-02T12:01:47    ERROR ] Task exception was never retrieved
future: <Task finished name='Task-8' coro=<_get() done, defined at /home/crodriguezde/experiments/reimage/venv/lib/python3.8/site-packages/backoff/_async.py:118> exception=KeyboardInterrupt()>
Traceback (most recent call last):
  File "deployer.py", line 150, in <module>
    main()
  File "deployer.py", line 137, in main
    asyncio.run(imds.get_from_vmss_vms(args))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
    handle._run()
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/home/crodriguezde/experiments/reimage/venv/lib/python3.8/site-packages/backoff/_async.py", line 133, in retry
    ret = await target(*args, **kwargs)
  File "/home/crodriguezde/experiments/reimage/imds.py", line 51, in _get
    instance_vm = _wait_vm_state_running(cli_args, vmss_vm)
  File "/home/crodriguezde/experiments/reimage/venv/lib/python3.8/site-packages/backoff/_sync.py", line 94, in retry
    ret = target(*args, **kwargs)
  File "/home/crodriguezde/experiments/reimage/venv/lib/python3.8/site-packages/backoff/_sync.py", line 43, in retry
    ret = target(*args, **kwargs)
  File "/home/crodriguezde/experiments/reimage/imds.py", line 96, in _wait_vm_state_running
    instance_vm = vm.get(args, vmss_vm)
  File "/home/crodriguezde/experiments/reimage/utils.py", line 14, in timer
    result = fn(*args, **kwargs)
  File "/home/crodriguezde/experiments/reimage/vm.py", line 31, in get
    return resource_client.virtual_machines.instance_view(
  File "/home/crodriguezde/experiments/reimage/venv/lib/python3.8/site-packages/azure/core/tracing/decorator.py", line 73, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/home/crodriguezde/experiments/reimage/venv/lib/python3.8/site-packages/azure/mgmt/compute/v2021_11_01/operations/_virtual_machines_operations.py", line 1626, in instance_view
    pipeline_response = self._client._pipeline.run(request, stream=False, **kwargs)
  File "/home/crodriguezde/experiments/reimage/venv/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 211, in run
    return first_node.send(pipeline_request)  # type: ignore
  File "/home/crodriguezde/experiments/reimage/venv/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/home/crodriguezde/experiments/reimage/venv/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/home/crodriguezde/experiments/reimage/venv/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  [Previous line repeated 2 more times]
  File "/home/crodriguezde/experiments/reimage/venv/lib/python3.8/site-packages/azure/mgmt/core/policies/_base.py", line 47, in send
    response = self.next.send(request)
  File "/home/crodriguezde/experiments/reimage/venv/lib/python3.8/site-packages/azure/core/pipeline/policies/_redirect.py", line 158, in send
    response = self.next.send(request)
  File "/home/crodriguezde/experiments/reimage/venv/lib/python3.8/site-packages/azure/core/pipeline/policies/_retry.py", line 445, in send
    response = self.next.send(request)
  File "/home/crodriguezde/experiments/reimage/venv/lib/python3.8/site-packages/azure/core/pipeline/policies/_authentication.py", line 117, in send
    self.on_request(request)
  File "/home/crodriguezde/experiments/reimage/venv/lib/python3.8/site-packages/azure/core/pipeline/policies/_authentication.py", line 94, in on_request
    self._token = self._credential.get_token(*self._scopes)
  File "/home/crodriguezde/experiments/reimage/venv/lib/python3.8/site-packages/azure/identity/_internal/decorators.py", line 32, in wrapper
    token = fn(*args, **kwargs)
  File "/home/crodriguezde/experiments/reimage/venv/lib/python3.8/site-packages/azure/identity/_credentials/azure_cli.py", line 73, in get_token
    output = _run_command(command)
  File "/home/crodriguezde/experiments/reimage/venv/lib/python3.8/site-packages/azure/identity/_credentials/azure_cli.py", line 141, in _run_command
    return subprocess.check_output(args, **kwargs)
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 495, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib/python3.8/subprocess.py", line 1028, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.8/subprocess.py", line 1868, in _communicate
    ready = selector.select(timeout)
  File "/usr/lib/python3.8/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt
