[ 2022-04-29T12:10:25     INFO ] logging to applications insights
[ 2022-04-29T12:10:26     INFO ] [ exists                   ] True
[ 2022-04-29T12:10:27     INFO ] [ get                      ] {'additional_properties': {}, 'id': '/subscriptions/b698965a-1f53-45ec-8b81-58458d1b25f7/resourceGroups/VMSSReImageRun1SOUTHCENTRALUS', 'name': 'VMSSReImageRun1SOUTHCENTRALUS', 'type': 'Microsoft.Resources/resourceGroups', 'properties': <azure.mgmt.resource.resources.v2021_04_01.models._models_py3.ResourceGroupProperties object at 0x7f5da1fd8d30>, 'location': 'southcentralus', 'managed_by': None, 'tags': None}
[ 2022-04-29T12:10:28     INFO ] [ create                   ] {'additional_properties': {}, 'id': '/subscriptions/b698965a-1f53-45ec-8b81-58458d1b25f7/resourceGroups/VMSSReImageRun1SOUTHCENTRALUS/providers/Microsoft.Storage/storageAccounts/vmsspipeline9fc2a6bc', 'name': 'vmsspipeline9fc2a6bc', 'type': 'Microsoft.Storage/storageAccounts', 'tags': {'confidentiality': 'public'}, 'location': 'southcentralus', 'sku': <azure.mgmt.storage.v2021_09_01.models._models_py3.Sku object at 0x7f5da1e14490>, 'kind': 'StorageV2', 'identity': None, 'extended_location': None, 'provisioning_state': 'Succeeded', 'primary_endpoints': <azure.mgmt.storage.v2021_09_01.models._models_py3.Endpoints object at 0x7f5da1e14a30>, 'primary_location': 'southcentralus', 'status_of_primary': 'available', 'last_geo_failover_time': None, 'secondary_location': None, 'status_of_secondary': None, 'creation_time': datetime.datetime(2022, 4, 29, 16, 7, 7, 364576, tzinfo=<isodate.tzinfo.Utc object at 0x7f5da5b215e0>), 'custom_domain': None, 'sas_policy': None, 'key_policy': None, 'key_creation_time': <azure.mgmt.storage.v2021_09_01.models._models_py3.KeyCreationTime object at 0x7f5da1e14c40>, 'secondary_endpoints': None, 'encryption': <azure.mgmt.storage.v2021_09_01.models._models_py3.Encryption object at 0x7f5da1e14a90>, 'access_tier': 'Hot', 'azure_files_identity_based_authentication': None, 'enable_https_traffic_only': True, 'network_rule_set': <azure.mgmt.storage.v2021_09_01.models._models_py3.NetworkRuleSet object at 0x7f5da1e14be0>, 'is_sftp_enabled': None, 'is_local_user_enabled': None, 'is_hns_enabled': None, 'geo_replication_stats': None, 'failover_in_progress': None, 'large_file_shares_state': None, 'private_endpoint_connections': [], 'routing_preference': None, 'blob_restore_status': None, 'allow_blob_public_access': True, 'minimum_tls_version': 'TLS1_0', 'allow_shared_key_access': None, 'enable_nfs_v3': None, 'allow_cross_tenant_replication': None, 'default_to_o_auth_authentication': None, 'public_network_access': None, 'immutable_storage_with_versioning': None, 'allowed_copy_scope': None, 'storage_account_sku_conversion_status': None, 'dns_endpoint_type': None}
[ 2022-04-29T12:10:29     INFO ] [ get                      ] {'additional_properties': {}, 'id': '/subscriptions/b698965a-1f53-45ec-8b81-58458d1b25f7/resourceGroups/VMSSReImageRun1SOUTHCENTRALUS/providers/Microsoft.Network/networkSecurityGroups/vmssPeregrineTest-nsg', 'name': 'vmssPeregrineTest-nsg', 'type': 'Microsoft.Network/networkSecurityGroups', 'location': 'southcentralus', 'tags': {'confidentiality': 'public'}, 'etag': 'W/"eb7d1979-ed01-4960-a05c-263594cf31d5"', 'security_rules': [<azure.mgmt.network.v2021_05_01.models._models_py3.SecurityRule object at 0x7f5da175aa60>], 'default_security_rules': [<azure.mgmt.network.v2021_05_01.models._models_py3.SecurityRule object at 0x7f5da175a970>, <azure.mgmt.network.v2021_05_01.models._models_py3.SecurityRule object at 0x7f5da175abb0>, <azure.mgmt.network.v2021_05_01.models._models_py3.SecurityRule object at 0x7f5da175abe0>, <azure.mgmt.network.v2021_05_01.models._models_py3.SecurityRule object at 0x7f5da175ac10>, <azure.mgmt.network.v2021_05_01.models._models_py3.SecurityRule object at 0x7f5da175ac40>, <azure.mgmt.network.v2021_05_01.models._models_py3.SecurityRule object at 0x7f5da175ac70>], 'network_interfaces': None, 'subnets': [<azure.mgmt.network.v2021_05_01.models._models_py3.Subnet object at 0x7f5da175acd0>], 'flow_logs': None, 'resource_guid': 'a66db6d6-770c-4f59-9ac2-c283de4a9a24', 'provisioning_state': 'Succeeded'}
[ 2022-04-29T12:10:30     INFO ] [ get                      ] {'additional_properties': {}, 'id': '/subscriptions/b698965a-1f53-45ec-8b81-58458d1b25f7/resourceGroups/VMSSReImageRun1SOUTHCENTRALUS/providers/Microsoft.Network/virtualNetworks/vmssPeregrineTest-vnet', 'name': 'vmssPeregrineTest-vnet', 'type': 'Microsoft.Network/virtualNetworks', 'location': 'southcentralus', 'tags': {'confidentiality': 'public'}, 'extended_location': None, 'etag': 'W/"d5b4eb7c-ea37-462b-9ea4-fbd232834c2c"', 'address_space': <azure.mgmt.network.v2021_05_01.models._models_py3.AddressSpace object at 0x7f5da175ae20>, 'dhcp_options': None, 'flow_timeout_in_minutes': None, 'subnets': [<azure.mgmt.network.v2021_05_01.models._models_py3.Subnet object at 0x7f5da1e14e20>], 'virtual_network_peerings': [], 'resource_guid': '0f1294d0-ba81-42f8-bd75-de499de66b2f', 'provisioning_state': 'Succeeded', 'enable_ddos_protection': False, 'enable_vm_protection': None, 'ddos_protection_plan': None, 'bgp_communities': None, 'encryption': None, 'ip_allocations': None}
[ 2022-04-29T12:10:30     INFO ] [ subnets_list             ] <iterator object azure.core.paging.ItemPaged at 0x7f5da1e14ee0>
[ 2022-04-29T12:10:31     INFO ] [ get                      ] {'additional_properties': {}, 'id': '/subscriptions/b698965a-1f53-45ec-8b81-58458d1b25f7/resourceGroups/VMSSReImageRun1SOUTHCENTRALUS/providers/Microsoft.Compute/virtualMachineScaleSets/vmssPeregrineTest', 'name': 'vmssPeregrineTest', 'type': 'Microsoft.Compute/virtualMachineScaleSets', 'location': 'southcentralus', 'tags': {'confidentiality': 'public'}, 'sku': <azure.mgmt.compute.v2021_11_01.models._models_py3.Sku object at 0x7f5da14cd760>, 'plan': None, 'identity': None, 'zones': ['1'], 'extended_location': None, 'upgrade_policy': None, 'automatic_repairs_policy': None, 'virtual_machine_profile': <azure.mgmt.compute.v2021_11_01.models._models_py3.VirtualMachineScaleSetVMProfile object at 0x7f5da14cdc70>, 'provisioning_state': 'Succeeded', 'overprovision': None, 'do_not_run_extensions_on_overprovisioned_v_ms': None, 'unique_id': '37746c0b-92b4-4b45-961f-474922163bb5', 'single_placement_group': False, 'zone_balance': None, 'platform_fault_domain_count': 1, 'proximity_placement_group': None, 'host_group': None, 'additional_capabilities': None, 'scale_in_policy': None, 'orchestration_mode': 'Flexible', 'spot_restore_policy': None, 'time_created': datetime.datetime(2022, 4, 29, 16, 7, 45, 135353, tzinfo=<FixedOffset '+00:00'>)}
[ 2022-04-29T12:10:31     INFO ] [ get_vms                  ] <iterator object azure.core.paging.ItemPaged at 0x7f5da1790130>
[ 2022-04-29T12:10:31    DEBUG ] Using selector: EpollSelector
[ 2022-04-29T12:10:31     INFO ] [ get_vms                  ] <iterator object azure.core.paging.ItemPaged at 0x7f5da145b9d0>
[ 2022-04-29T12:10:32     INFO ] Finish queuing all vms
[ 2022-04-29T12:10:32     INFO ] [ get                      ] {'additional_properties': {}, 'platform_update_domain': None, 'platform_fault_domain': None, 'computer_name': 'vmInstance1OE4NY', 'os_name': 'ubuntu', 'os_version': '18.04', 'hyper_v_generation': 'V1', 'rdp_thumb_print': None, 'vm_agent': <azure.mgmt.compute.v2021_11_01.models._models_py3.VirtualMachineAgentInstanceView object at 0x7f5da1488d00>, 'maintenance_redeploy_status': None, 'disks': [<azure.mgmt.compute.v2021_11_01.models._models_py3.DiskInstanceView object at 0x7f5da1488ee0>], 'extensions': [], 'vm_health': None, 'boot_diagnostics': <azure.mgmt.compute.v2021_11_01.models._models_py3.BootDiagnosticsInstanceView object at 0x7f5da1488d90>, 'assigned_host': None, 'statuses': [<azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f5da148c070>, <azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f5da148c0a0>], 'patch_status': None}
[ 2022-04-29T12:10:33     INFO ] [ get                      ] {'additional_properties': {}, 'platform_update_domain': None, 'platform_fault_domain': None, 'computer_name': 'vmInstance1ZB63N', 'os_name': 'ubuntu', 'os_version': '18.04', 'hyper_v_generation': 'V1', 'rdp_thumb_print': None, 'vm_agent': <azure.mgmt.compute.v2021_11_01.models._models_py3.VirtualMachineAgentInstanceView object at 0x7f5da067d0d0>, 'maintenance_redeploy_status': None, 'disks': [<azure.mgmt.compute.v2021_11_01.models._models_py3.DiskInstanceView object at 0x7f5da067d2b0>], 'extensions': [], 'vm_health': None, 'boot_diagnostics': <azure.mgmt.compute.v2021_11_01.models._models_py3.BootDiagnosticsInstanceView object at 0x7f5da067d160>, 'assigned_host': None, 'statuses': [<azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f5da067d400>, <azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f5da067d430>], 'patch_status': None}
[ 2022-04-29T12:10:33     INFO ] [ get                      ] {'additional_properties': {}, 'platform_update_domain': None, 'platform_fault_domain': None, 'computer_name': 'vmInstance2C0PSP', 'os_name': 'ubuntu', 'os_version': '18.04', 'hyper_v_generation': 'V1', 'rdp_thumb_print': None, 'vm_agent': <azure.mgmt.compute.v2021_11_01.models._models_py3.VirtualMachineAgentInstanceView object at 0x7f5da06834f0>, 'maintenance_redeploy_status': None, 'disks': [<azure.mgmt.compute.v2021_11_01.models._models_py3.DiskInstanceView object at 0x7f5da06836d0>], 'extensions': [], 'vm_health': None, 'boot_diagnostics': <azure.mgmt.compute.v2021_11_01.models._models_py3.BootDiagnosticsInstanceView object at 0x7f5da0683580>, 'assigned_host': None, 'statuses': [<azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f5da0683820>, <azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f5da0683850>], 'patch_status': None}
[ 2022-04-29T12:10:34     INFO ] [ get                      ] {'additional_properties': {}, 'platform_update_domain': None, 'platform_fault_domain': None, 'computer_name': 'vmInstance2RNIEP', 'os_name': 'ubuntu', 'os_version': '18.04', 'hyper_v_generation': 'V1', 'rdp_thumb_print': None, 'vm_agent': <azure.mgmt.compute.v2021_11_01.models._models_py3.VirtualMachineAgentInstanceView object at 0x7f5da0688a90>, 'maintenance_redeploy_status': None, 'disks': [<azure.mgmt.compute.v2021_11_01.models._models_py3.DiskInstanceView object at 0x7f5da0688c70>], 'extensions': [], 'vm_health': None, 'boot_diagnostics': <azure.mgmt.compute.v2021_11_01.models._models_py3.BootDiagnosticsInstanceView object at 0x7f5da0688a30>, 'assigned_host': None, 'statuses': [<azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f5da0688df0>, <azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f5da0688e20>], 'patch_status': None}
[ 2022-04-29T12:10:35     INFO ] [ get                      ] {'additional_properties': {}, 'platform_update_domain': None, 'platform_fault_domain': None, 'computer_name': 'vmInstance2UT10B', 'os_name': 'ubuntu', 'os_version': '18.04', 'hyper_v_generation': 'V1', 'rdp_thumb_print': None, 'vm_agent': <azure.mgmt.compute.v2021_11_01.models._models_py3.VirtualMachineAgentInstanceView object at 0x7f5da061c8e0>, 'maintenance_redeploy_status': None, 'disks': [<azure.mgmt.compute.v2021_11_01.models._models_py3.DiskInstanceView object at 0x7f5da061cac0>], 'extensions': [], 'vm_health': None, 'boot_diagnostics': <azure.mgmt.compute.v2021_11_01.models._models_py3.BootDiagnosticsInstanceView object at 0x7f5da061c970>, 'assigned_host': None, 'statuses': [<azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f5da061cc10>, <azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f5da061cc40>], 'patch_status': None}
[ 2022-04-29T12:10:35     INFO ] [ get                      ] {'additional_properties': {}, 'platform_update_domain': None, 'platform_fault_domain': None, 'computer_name': 'vmInstance3BVHI3', 'os_name': 'ubuntu', 'os_version': '18.04', 'hyper_v_generation': 'V1', 'rdp_thumb_print': None, 'vm_agent': <azure.mgmt.compute.v2021_11_01.models._models_py3.VirtualMachineAgentInstanceView object at 0x7f5da061c0d0>, 'maintenance_redeploy_status': None, 'disks': [<azure.mgmt.compute.v2021_11_01.models._models_py3.DiskInstanceView object at 0x7f5da062a6a0>], 'extensions': [], 'vm_health': None, 'boot_diagnostics': <azure.mgmt.compute.v2021_11_01.models._models_py3.BootDiagnosticsInstanceView object at 0x7f5da061c040>, 'assigned_host': None, 'statuses': [<azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f5da062a7c0>, <azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f5da062a970>], 'patch_status': None}
[ 2022-04-29T12:10:36     INFO ] [ get                      ] {'additional_properties': {}, 'platform_update_domain': None, 'platform_fault_domain': None, 'computer_name': 'vmInstance3NM16Y', 'os_name': 'ubuntu', 'os_version': '18.04', 'hyper_v_generation': 'V1', 'rdp_thumb_print': None, 'vm_agent': <azure.mgmt.compute.v2021_11_01.models._models_py3.VirtualMachineAgentInstanceView object at 0x7f5da0623a60>, 'maintenance_redeploy_status': None, 'disks': [<azure.mgmt.compute.v2021_11_01.models._models_py3.DiskInstanceView object at 0x7f5da0623c40>], 'extensions': [], 'vm_health': None, 'boot_diagnostics': <azure.mgmt.compute.v2021_11_01.models._models_py3.BootDiagnosticsInstanceView object at 0x7f5da0623af0>, 'assigned_host': None, 'statuses': [<azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f5da0623d90>, <azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f5da0623dc0>], 'patch_status': None}
[ 2022-04-29T12:10:37  WARNING ] AzureCliCredential.get_token failed: Unexpected output from Azure CLI: '--- Logging error ---
Traceback (most recent call last):
  File "/home/crodriguezde/.local/lib/python3.8/site-packages/azure/cli/__main__.py", line 60, in <module>
    raise ex
  File "/home/crodriguezde/.local/lib/python3.8/site-packages/azure/cli/__main__.py", line 53, in <module>
    sys.exit(exit_code)
SystemExit: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/handlers.py", line 70, in emit
    self.doRollover()
  File "/usr/lib/python3.8/logging/handlers.py", line 167, in doRollover
    os.rename(sfn, dfn)
FileNotFoundError: [Errno 2] No such file or directory: '/home/crodriguezde/.azure/telemetry/cache.2' -> '/home/crodriguezde/.azure/telemetry/cache.3'
Call stack:
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/crodriguezde/.local/lib/python3.8/site-packages/azure/cli/__main__.py", line 123, in <module>
    telemetry.conclude()
  File "/home/crodriguezde/.local/lib/python3.8/site-packages/azure/cli/core/telemetry.py", line 241, in _wrapper
    return func(*args, **kwargs)
  File "/home/crodriguezde/.local/lib/python3.8/site-packages/azure/cli/core/decorators.py", line 79, in _wrapped_func
    return func(*args, **kwargs)
  File "/home/crodriguezde/.local/lib/python3.8/site-packages/azure/cli/core/telemetry.py", line 297, in conclude
    save(get_config_dir(), _session.generate_payload())
  File "/home/crodriguezde/.local/lib/python3.8/site-packages/azure/cli/telemetry/__init__.py", line 51, in save
    if save_payload(config_dir, payload) and should_upload(config_dir):
  File "/home/crodriguezde/.local/lib/python3.8/site-packages/azure/cli/telemetry/util.py", line 53, in save_payload
    cache_saver.info(payload)
Message: '{"c4395b75-49cc-422c-bc95-c7d51aef5d46":[{"name":"azurecli/command","properties":{"Reserved.DataModel.EntityType":"UserTask","Reserved.DataModel.Action.Type":"Atomic","Reserved.DataModel.Action.Result":"Success","Reserved.ChannelUsed":"AI","Reserved.EventId":"cae52de0-d6cd-4e0e-85ff-0a0af68b16fe","Reserved.SequenceNumber":1,"Reserved.SessionId":"d39c80d9e35064901a1a5dc1bd188854e52fde430638dd3b086a2a2ab58ba314","Reserved.TimeSinceSessionStart":0,"Reserved.DataModel.Source":"DataModelAPI","Reserved.DataModel.EntitySchemaVersion":4,"Reserved.DataModel.Severity":0,"Reserved.DataModel.ProductName":"azurecli","Reserved.DataModel.FeatureName":"command","Reserved.DataModel.EntityName":"account-getaccesstoken","Reserved.DataModel.CorrelationId":"220a1751-ec0e-4e76-980a-da0eec1d6a3a","Context.Default.VS.Core.ExeName":"azurecli","Context.Default.VS.Core.ExeVersion":"2.35.0@none","Context.Default.VS.Core.MacAddressHash":"e9bfd1348393ff8f258c5b795e82bf541f4459c5b4d6fa911e34d480ac33d348","Context.Default.VS.Core.Machine.Id":"e9bfd134-8393-ff8f-258c-5b795e82bf54","Context.Default.VS.Core.OS.Type":"linux","Context.Default.VS.Core.OS.Version":"#1 smp wed mar 2 00:30:59 utc 2022","Context.Default.VS.Core.OS.Platform":"linux-5.10.102.1-microsoft-standard-wsl2-x86_64-with-glibc2.29","Context.Default.VS.Core.User.Id":"64c5b0af-e344-11eb-b316-c03c59895c0a","Context.Default.VS.Core.User.IsMicrosoftInternal":"False","Context.Default.VS.Core.User.IsOptedIn":"True","Context.Default.VS.Core.TelemetryApi.ProductVersion":"azurecli@2.35.0","Context.Default.AzureCLI.Source":"az","Context.Default.AzureCLI.ClientRequestId":"49a086ae-c7df-11ec-aa60-00155d785913","Context.Default.AzureCLI.CoreVersion":"2.35.0","Context.Default.AzureCLI.TelemetryVersion":"2.0","Context.Default.AzureCLI.InstallationId":"64c5b0af-e344-11eb-b316-c03c59895c0a","Context.Default.AzureCLI.ShellType":"/usr/bin/zsh","Context.Default.AzureCLI.UserAzureId":"39921e2f44771b3d76a90cf4cac837fdf8e646729bbbcbe017a174f2298b5c4c","Context.Default.AzureCLI.UserAzureSubscriptionId":"b698965a-1f53-45ec-8b81-58458d1b25f7","Context.Default.AzureCLI.DefaultOutputType":"unknown","Context.Default.AzureCLI.EnvironmentVariables":"[]","Context.Default.AzureCLI.Locale":"en_US,UTF-8","Context.Default.AzureCLI.StartTime":"2022-04-29 17:10:36.840311","Context.Default.AzureCLI.EndTime":"2022-04-29 17:10:37.013727","Context.Default.AzureCLI.InitTimeElapsed":"0.116923","Context.Default.AzureCLI.InvokeTimeElapsed":"0.169912","Context.Default.AzureCLI.OutputType":"json","Context.Default.AzureCLI.RawCommand":"account get-access-token","Context.Default.AzureCLI.Params":"--output,--resource","Context.Default.AzureCLI.PythonVersion":"3.8.10","Context.Default.AzureCLI.Mode":"default","Context.Default.AzureCLI.Installer":"PIP","Context.Default.AzureCLI.error_type":"None","Context.Default.AzureCLI.exception_name":"None","Context.Default.AzureCLI.debug_info":"","Context.Default.AzureCLI.PollStartTime":"None","Context.Default.AzureCLI.PollEndTime":"None"}}]}'
Arguments: ()
{
  ****,
  "expiresOn": "2022-04-29 13:01:18.000000",
  "subscription": "b698965a-1f53-45ec-8b81-58458d1b25f7",
  "tenant": "72f988bf-86f1-41af-91ab-2d7cd011db47",
  "tokenType": "Bearer"
}
'. 
To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/python/identity/azclicredential/troubleshoot.
[ 2022-04-29T12:10:38     INFO ] [ get                      ] {'additional_properties': {}, 'platform_update_domain': None, 'platform_fault_domain': None, 'computer_name': 'vmInstance46BHVP', 'os_name': 'ubuntu', 'os_version': '18.04', 'hyper_v_generation': 'V1', 'rdp_thumb_print': None, 'vm_agent': <azure.mgmt.compute.v2021_11_01.models._models_py3.VirtualMachineAgentInstanceView object at 0x7f5da0639ac0>, 'maintenance_redeploy_status': None, 'disks': [<azure.mgmt.compute.v2021_11_01.models._models_py3.DiskInstanceView object at 0x7f5da0639ca0>], 'extensions': [], 'vm_health': None, 'boot_diagnostics': <azure.mgmt.compute.v2021_11_01.models._models_py3.BootDiagnosticsInstanceView object at 0x7f5da0639b50>, 'assigned_host': None, 'statuses': [<azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f5da0639df0>, <azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f5da0639e20>], 'patch_status': None}
[ 2022-04-29T12:10:39     INFO ] [ get                      ] {'additional_properties': {}, 'platform_update_domain': None, 'platform_fault_domain': None, 'computer_name': 'vmInstance4MZ3H7', 'os_name': 'ubuntu', 'os_version': '18.04', 'hyper_v_generation': 'V1', 'rdp_thumb_print': None, 'vm_agent': <azure.mgmt.compute.v2021_11_01.models._models_py3.VirtualMachineAgentInstanceView object at 0x7f5da064a0d0>, 'maintenance_redeploy_status': None, 'disks': [<azure.mgmt.compute.v2021_11_01.models._models_py3.DiskInstanceView object at 0x7f5da064a2b0>], 'extensions': [], 'vm_health': None, 'boot_diagnostics': <azure.mgmt.compute.v2021_11_01.models._models_py3.BootDiagnosticsInstanceView object at 0x7f5da064a160>, 'assigned_host': None, 'statuses': [<azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f5da064a400>, <azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f5da064a430>], 'patch_status': None}
[ 2022-04-29T12:10:39     INFO ] [ get                      ] {'additional_properties': {}, 'platform_update_domain': None, 'platform_fault_domain': None, 'computer_name': 'vmInstance4TUB0I', 'os_name': 'ubuntu', 'os_version': '18.04', 'hyper_v_generation': 'V1', 'rdp_thumb_print': None, 'vm_agent': <azure.mgmt.compute.v2021_11_01.models._models_py3.VirtualMachineAgentInstanceView object at 0x7f5da0650430>, 'maintenance_redeploy_status': None, 'disks': [<azure.mgmt.compute.v2021_11_01.models._models_py3.DiskInstanceView object at 0x7f5da0650610>], 'extensions': [], 'vm_health': None, 'boot_diagnostics': <azure.mgmt.compute.v2021_11_01.models._models_py3.BootDiagnosticsInstanceView object at 0x7f5da06504c0>, 'assigned_host': None, 'statuses': [<azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f5da0650760>, <azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f5da0650790>], 'patch_status': None}
[ 2022-04-29T12:10:40    DEBUG ] Encoding detection on empty bytes, assuming utf_8 intention.
[ 2022-04-29T12:10:40    DEBUG ] Encoding detection on empty bytes, assuming utf_8 intention.
[ 2022-04-29T12:10:40    DEBUG ] Encoding detection on empty bytes, assuming utf_8 intention.
[ 2022-04-29T12:10:40    DEBUG ] Encoding detection on empty bytes, assuming utf_8 intention.
[ 2022-04-29T12:10:40    DEBUG ] Encoding detection on empty bytes, assuming utf_8 intention.
[ 2022-04-29T12:10:40    DEBUG ] Encoding detection on empty bytes, assuming utf_8 intention.
[ 2022-04-29T12:10:40    DEBUG ] Encoding detection on empty bytes, assuming utf_8 intention.
[ 2022-04-29T12:10:40    DEBUG ] Encoding detection on empty bytes, assuming utf_8 intention.
[ 2022-04-29T12:10:40    DEBUG ] Encoding detection on empty bytes, assuming utf_8 intention.
[ 2022-04-29T12:10:40    DEBUG ] Encoding detection on empty bytes, assuming utf_8 intention.
[ 2022-04-29T12:11:11     INFO ] [ get                      ] {'additional_properties': {}, 'platform_update_domain': None, 'platform_fault_domain': None, 'computer_name': 'vmInstance6J1CJ8', 'os_name': 'ubuntu', 'os_version': '18.04', 'hyper_v_generation': 'V1', 'rdp_thumb_print': None, 'vm_agent': <azure.mgmt.compute.v2021_11_01.models._models_py3.VirtualMachineAgentInstanceView object at 0x7f5da05dbe80>, 'maintenance_redeploy_status': None, 'disks': [<azure.mgmt.compute.v2021_11_01.models._models_py3.DiskInstanceView object at 0x7f5da05660a0>], 'extensions': [], 'vm_health': None, 'boot_diagnostics': <azure.mgmt.compute.v2021_11_01.models._models_py3.BootDiagnosticsInstanceView object at 0x7f5da05dbf10>, 'assigned_host': None, 'statuses': [<azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f5da05661f0>, <azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f5da0566220>], 'patch_status': None}
[ 2022-04-29T12:11:11     INFO ] [ get                      ] {'additional_properties': {}, 'platform_update_domain': None, 'platform_fault_domain': None, 'computer_name': 'vmInstance7LN82P', 'os_name': 'ubuntu', 'os_version': '18.04', 'hyper_v_generation': 'V1', 'rdp_thumb_print': None, 'vm_agent': <azure.mgmt.compute.v2021_11_01.models._models_py3.VirtualMachineAgentInstanceView object at 0x7f5da0572580>, 'maintenance_redeploy_status': None, 'disks': [<azure.mgmt.compute.v2021_11_01.models._models_py3.DiskInstanceView object at 0x7f5da0572760>], 'extensions': [], 'vm_health': None, 'boot_diagnostics': <azure.mgmt.compute.v2021_11_01.models._models_py3.BootDiagnosticsInstanceView object at 0x7f5da0572610>, 'assigned_host': None, 'statuses': [<azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f5da05728b0>, <azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f5da05728e0>], 'patch_status': None}
[ 2022-04-29T12:11:12     INFO ] [ get                      ] {'additional_properties': {}, 'platform_update_domain': None, 'platform_fault_domain': None, 'computer_name': 'vmInstance7T6J4T', 'os_name': 'ubuntu', 'os_version': '18.04', 'hyper_v_generation': 'V1', 'rdp_thumb_print': None, 'vm_agent': <azure.mgmt.compute.v2021_11_01.models._models_py3.VirtualMachineAgentInstanceView object at 0x7f5da05d2ac0>, 'maintenance_redeploy_status': None, 'disks': [<azure.mgmt.compute.v2021_11_01.models._models_py3.DiskInstanceView object at 0x7f5da05bce50>], 'extensions': [], 'vm_health': None, 'boot_diagnostics': <azure.mgmt.compute.v2021_11_01.models._models_py3.BootDiagnosticsInstanceView object at 0x7f5da05d2b50>, 'assigned_host': None, 'statuses': [<azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f5da05bcfd0>, <azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f5da05bc580>], 'patch_status': None}
[ 2022-04-29T12:11:13     INFO ] [ get                      ] {'additional_properties': {}, 'platform_update_domain': None, 'platform_fault_domain': None, 'computer_name': 'vmInstance8OF109', 'os_name': 'ubuntu', 'os_version': '18.04', 'hyper_v_generation': 'V1', 'rdp_thumb_print': None, 'vm_agent': <azure.mgmt.compute.v2021_11_01.models._models_py3.VirtualMachineAgentInstanceView object at 0x7f5da0623e50>, 'maintenance_redeploy_status': None, 'disks': [<azure.mgmt.compute.v2021_11_01.models._models_py3.DiskInstanceView object at 0x7f5da06233a0>], 'extensions': [], 'vm_health': None, 'boot_diagnostics': <azure.mgmt.compute.v2021_11_01.models._models_py3.BootDiagnosticsInstanceView object at 0x7f5da0623e80>, 'assigned_host': None, 'statuses': [<azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f5da0570160>, <azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f5da05707c0>], 'patch_status': None}
[ 2022-04-29T12:11:13     INFO ] [ get                      ] {'additional_properties': {}, 'platform_update_domain': None, 'platform_fault_domain': None, 'computer_name': 'vmInstance8Y7YDL', 'os_name': 'ubuntu', 'os_version': '18.04', 'hyper_v_generation': 'V1', 'rdp_thumb_print': None, 'vm_agent': <azure.mgmt.compute.v2021_11_01.models._models_py3.VirtualMachineAgentInstanceView object at 0x7f5da0572910>, 'maintenance_redeploy_status': None, 'disks': [<azure.mgmt.compute.v2021_11_01.models._models_py3.DiskInstanceView object at 0x7f5da0572af0>], 'extensions': [], 'vm_health': None, 'boot_diagnostics': <azure.mgmt.compute.v2021_11_01.models._models_py3.BootDiagnosticsInstanceView object at 0x7f5da05729a0>, 'assigned_host': None, 'statuses': [<azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f5da0572c40>, <azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f5da0572c70>], 'patch_status': None}
[ 2022-04-29T12:11:14     INFO ] [ get                      ] {'additional_properties': {}, 'platform_update_domain': None, 'platform_fault_domain': None, 'computer_name': 'vmInstance91S4YT', 'os_name': 'ubuntu', 'os_version': '18.04', 'hyper_v_generation': 'V1', 'rdp_thumb_print': None, 'vm_agent': <azure.mgmt.compute.v2021_11_01.models._models_py3.VirtualMachineAgentInstanceView object at 0x7f5da06934f0>, 'maintenance_redeploy_status': None, 'disks': [<azure.mgmt.compute.v2021_11_01.models._models_py3.DiskInstanceView object at 0x7f5da0592190>], 'extensions': [], 'vm_health': None, 'boot_diagnostics': <azure.mgmt.compute.v2021_11_01.models._models_py3.BootDiagnosticsInstanceView object at 0x7f5da067db50>, 'assigned_host': None, 'statuses': [<azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f5da05922e0>, <azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f5da0592310>], 'patch_status': None}
[ 2022-04-29T12:11:15     INFO ] [ get                      ] {'additional_properties': {}, 'platform_update_domain': None, 'platform_fault_domain': None, 'computer_name': 'vmInstance9PSKLN', 'os_name': 'ubuntu', 'os_version': '18.04', 'hyper_v_generation': 'V1', 'rdp_thumb_print': None, 'vm_agent': <azure.mgmt.compute.v2021_11_01.models._models_py3.VirtualMachineAgentInstanceView object at 0x7f5da0592d90>, 'maintenance_redeploy_status': None, 'disks': [<azure.mgmt.compute.v2021_11_01.models._models_py3.DiskInstanceView object at 0x7f5da0592f70>], 'extensions': [], 'vm_health': None, 'boot_diagnostics': <azure.mgmt.compute.v2021_11_01.models._models_py3.BootDiagnosticsInstanceView object at 0x7f5da0592e20>, 'assigned_host': None, 'statuses': [<azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f5da0598100>, <azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f5da0598130>], 'patch_status': None}
[ 2022-04-29T12:11:20     INFO ] [ get                      ] {'additional_properties': {}, 'platform_update_domain': None, 'platform_fault_domain': None, 'computer_name': 'vmInstanceAIQZ3V', 'os_name': 'ubuntu', 'os_version': '18.04', 'hyper_v_generation': 'V1', 'rdp_thumb_print': None, 'vm_agent': <azure.mgmt.compute.v2021_11_01.models._models_py3.VirtualMachineAgentInstanceView object at 0x7f5da0598c10>, 'maintenance_redeploy_status': None, 'disks': [<azure.mgmt.compute.v2021_11_01.models._models_py3.DiskInstanceView object at 0x7f5da0598df0>], 'extensions': [], 'vm_health': None, 'boot_diagnostics': <azure.mgmt.compute.v2021_11_01.models._models_py3.BootDiagnosticsInstanceView object at 0x7f5da0598ca0>, 'assigned_host': None, 'statuses': [<azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f5da0598f40>, <azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f5da0598f70>], 'patch_status': None}
[ 2022-04-29T12:11:21     INFO ] [ get                      ] {'additional_properties': {}, 'platform_update_domain': None, 'platform_fault_domain': None, 'computer_name': 'vmInstanceBEHG6E', 'os_name': 'ubuntu', 'os_version': '18.04', 'hyper_v_generation': 'V1', 'rdp_thumb_print': None, 'vm_agent': <azure.mgmt.compute.v2021_11_01.models._models_py3.VirtualMachineAgentInstanceView object at 0x7f5da051f940>, 'maintenance_redeploy_status': None, 'disks': [<azure.mgmt.compute.v2021_11_01.models._models_py3.DiskInstanceView object at 0x7f5da051fb50>], 'extensions': [], 'vm_health': None, 'boot_diagnostics': <azure.mgmt.compute.v2021_11_01.models._models_py3.BootDiagnosticsInstanceView object at 0x7f5da051f670>, 'assigned_host': None, 'statuses': [<azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f5da051fe20>, <azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f5da051fcd0>], 'patch_status': None}
[ 2022-04-29T12:11:22     INFO ] [ get                      ] {'additional_properties': {}, 'platform_update_domain': None, 'platform_fault_domain': None, 'computer_name': 'vmInstanceBWHIYH', 'os_name': 'ubuntu', 'os_version': '18.04', 'hyper_v_generation': 'V1', 'rdp_thumb_print': None, 'vm_agent': <azure.mgmt.compute.v2021_11_01.models._models_py3.VirtualMachineAgentInstanceView object at 0x7f5da0530b80>, 'maintenance_redeploy_status': None, 'disks': [<azure.mgmt.compute.v2021_11_01.models._models_py3.DiskInstanceView object at 0x7f5da0530d60>], 'extensions': [], 'vm_health': None, 'boot_diagnostics': <azure.mgmt.compute.v2021_11_01.models._models_py3.BootDiagnosticsInstanceView object at 0x7f5da0530c10>, 'assigned_host': None, 'statuses': [<azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f5da0530eb0>, <azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f5da0530ee0>], 'patch_status': None}
[ 2022-04-29T12:11:22    DEBUG ] Encoding detection on empty bytes, assuming utf_8 intention.
[ 2022-04-29T12:11:22    DEBUG ] Encoding detection on empty bytes, assuming utf_8 intention.
[ 2022-04-29T12:11:22    DEBUG ] Encoding detection on empty bytes, assuming utf_8 intention.
[ 2022-04-29T12:11:22    DEBUG ] Encoding detection on empty bytes, assuming utf_8 intention.
[ 2022-04-29T12:11:22    DEBUG ] Encoding detection on empty bytes, assuming utf_8 intention.
[ 2022-04-29T12:11:22    DEBUG ] Encoding detection on empty bytes, assuming utf_8 intention.
[ 2022-04-29T12:11:22    DEBUG ] Encoding detection on empty bytes, assuming utf_8 intention.
[ 2022-04-29T12:11:22    DEBUG ] Encoding detection on empty bytes, assuming utf_8 intention.
[ 2022-04-29T12:11:22    DEBUG ] Encoding detection on empty bytes, assuming utf_8 intention.
[ 2022-04-29T12:11:22    DEBUG ] Encoding detection on empty bytes, assuming utf_8 intention.
[ 2022-04-29T12:11:34    ERROR ] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f5da05985b0>
[ 2022-04-29T12:11:34    ERROR ] Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f5da05b82e0>, 697003.957095409)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f5da0572d60>
[ 2022-04-29T12:11:34    ERROR ] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f5da0570df0>
[ 2022-04-29T12:11:34    ERROR ] Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f5da0591760>, 697003.958784473)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f5da0570d00>
[ 2022-04-29T12:11:34    ERROR ] Task exception was never retrieved
future: <Task finished name='Task-2' coro=<logging_worker() done, defined at /home/crodriguezde/experiments/reimage/imds.py:37> exception=NameError("name 'raw' is not defined")>
Traceback (most recent call last):
  File "/home/crodriguezde/experiments/reimage/imds.py", line 40, in logging_worker
    logger_retry(msg)
  File "/home/crodriguezde/experiments/reimage/venv/lib/python3.8/site-packages/backoff/_sync.py", line 94, in retry
    ret = target(*args, **kwargs)
  File "/home/crodriguezde/experiments/reimage/imds.py", line 34, in logger_retry
    utils.log_imds(imds)
  File "/home/crodriguezde/experiments/reimage/utils.py", line 22, in log_imds
    'custom_dimensions': raw
NameError: name 'raw' is not defined
[ 2022-04-29T12:11:34    ERROR ] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f5da05a0e20>
[ 2022-04-29T12:11:34    ERROR ] Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f5da05c2a00>, 697003.950649691)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f5da05a09a0>
[ 2022-04-29T12:11:34    ERROR ] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f5da05c6730>
[ 2022-04-29T12:11:34    ERROR ] Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f5da056b640>, 697003.95362333)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f5da05c6ca0>
[ 2022-04-29T12:11:34    ERROR ] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f5da05923d0>
[ 2022-04-29T12:11:34    ERROR ] Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f5da05cd4c0>, 697004.703157201)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f5da0598550>
[ 2022-04-29T12:11:34    ERROR ] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f5da05dbca0>
[ 2022-04-29T12:11:34    ERROR ] Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f5da05b86a0>, 697003.952123693)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f5da0598340>
[ 2022-04-29T12:11:34    ERROR ] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f5da0598430>
[ 2022-04-29T12:11:34    ERROR ] Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f5da05c24c0>, 697003.960588396)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f5da05ace80>
[ 2022-04-29T12:11:34    ERROR ] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f5da067da00>
[ 2022-04-29T12:11:34    ERROR ] Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f5da05b8340>, 697003.955220031)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f5da0598250>
[ 2022-04-29T12:11:34    ERROR ] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f5da05d2850>
[ 2022-04-29T12:11:34    ERROR ] Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f5da05c2340>, 697003.947761152)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f5da05d2100>
[ 2022-04-29T12:11:34    ERROR ] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f5da0570760>
[ 2022-04-29T12:11:34    ERROR ] Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f5da052c820>, 697004.200255064)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f5da051faf0>
[ 2022-04-29T12:11:34     INFO ] Exit per user request
