[ 2022-04-27T20:38:54     INFO ] logging to applications insights
[ 2022-04-27T20:38:55     INFO ] [ exists                   ] True
[ 2022-04-27T20:38:56     INFO ] [ get                      ] {'additional_properties': {}, 'id': '/subscriptions/b698965a-1f53-45ec-8b81-58458d1b25f7/resourceGroups/VMSSReImageRun1SOUTHCENTRALUS', 'name': 'VMSSReImageRun1SOUTHCENTRALUS', 'type': 'Microsoft.Resources/resourceGroups', 'properties': <azure.mgmt.resource.resources.v2021_04_01.models._models_py3.ResourceGroupProperties object at 0x7fc9237b8400>, 'location': 'southcentralus', 'managed_by': None, 'tags': None}
[ 2022-04-27T20:38:58     INFO ] [ create                   ] {'additional_properties': {}, 'id': '/subscriptions/b698965a-1f53-45ec-8b81-58458d1b25f7/resourceGroups/VMSSReImageRun1SOUTHCENTRALUS/providers/Microsoft.Storage/storageAccounts/vmsspipeline9fc2a6bc', 'name': 'vmsspipeline9fc2a6bc', 'type': 'Microsoft.Storage/storageAccounts', 'tags': {'confidentiality': 'public'}, 'location': 'southcentralus', 'sku': <azure.mgmt.storage.v2021_09_01.models._models_py3.Sku object at 0x7fc9235d6d90>, 'kind': 'StorageV2', 'identity': None, 'extended_location': None, 'provisioning_state': 'Succeeded', 'primary_endpoints': <azure.mgmt.storage.v2021_09_01.models._models_py3.Endpoints object at 0x7fc9235d6af0>, 'primary_location': 'southcentralus', 'status_of_primary': 'available', 'last_geo_failover_time': None, 'secondary_location': None, 'status_of_secondary': None, 'creation_time': datetime.datetime(2022, 4, 26, 16, 3, 34, 184382, tzinfo=<isodate.tzinfo.Utc object at 0x7fc93330b610>), 'custom_domain': None, 'sas_policy': None, 'key_policy': None, 'key_creation_time': <azure.mgmt.storage.v2021_09_01.models._models_py3.KeyCreationTime object at 0x7fc9235e3070>, 'secondary_endpoints': None, 'encryption': <azure.mgmt.storage.v2021_09_01.models._models_py3.Encryption object at 0x7fc9235e3340>, 'access_tier': 'Hot', 'azure_files_identity_based_authentication': None, 'enable_https_traffic_only': True, 'network_rule_set': <azure.mgmt.storage.v2021_09_01.models._models_py3.NetworkRuleSet object at 0x7fc9235e35e0>, 'is_sftp_enabled': None, 'is_local_user_enabled': None, 'is_hns_enabled': None, 'geo_replication_stats': None, 'failover_in_progress': None, 'large_file_shares_state': None, 'private_endpoint_connections': [], 'routing_preference': None, 'blob_restore_status': None, 'allow_blob_public_access': True, 'minimum_tls_version': 'TLS1_0', 'allow_shared_key_access': None, 'enable_nfs_v3': None, 'allow_cross_tenant_replication': None, 'default_to_o_auth_authentication': None, 'public_network_access': None, 'immutable_storage_with_versioning': None, 'allowed_copy_scope': None, 'storage_account_sku_conversion_status': None, 'dns_endpoint_type': None}
[ 2022-04-27T20:38:58     INFO ] [ get                      ] {'additional_properties': {}, 'id': '/subscriptions/b698965a-1f53-45ec-8b81-58458d1b25f7/resourceGroups/VMSSReImageRun1SOUTHCENTRALUS/providers/Microsoft.Network/networkSecurityGroups/vmssPeregrineTest-nsg', 'name': 'vmssPeregrineTest-nsg', 'type': 'Microsoft.Network/networkSecurityGroups', 'location': 'southcentralus', 'tags': {'confidentiality': 'public'}, 'etag': 'W/"032dcc53-bfb9-4cda-95f8-9d8fe45e7237"', 'security_rules': [<azure.mgmt.network.v2021_05_01.models._models_py3.SecurityRule object at 0x7fc922f2d160>], 'default_security_rules': [<azure.mgmt.network.v2021_05_01.models._models_py3.SecurityRule object at 0x7fc922f2d070>, <azure.mgmt.network.v2021_05_01.models._models_py3.SecurityRule object at 0x7fc922f2d190>, <azure.mgmt.network.v2021_05_01.models._models_py3.SecurityRule object at 0x7fc922f2d1c0>, <azure.mgmt.network.v2021_05_01.models._models_py3.SecurityRule object at 0x7fc922f2d1f0>, <azure.mgmt.network.v2021_05_01.models._models_py3.SecurityRule object at 0x7fc922f2d220>, <azure.mgmt.network.v2021_05_01.models._models_py3.SecurityRule object at 0x7fc922f2d250>], 'network_interfaces': None, 'subnets': [<azure.mgmt.network.v2021_05_01.models._models_py3.Subnet object at 0x7fc922f2d2b0>], 'flow_logs': None, 'resource_guid': '203bc10e-1f08-45fe-8574-0dda31091c3d', 'provisioning_state': 'Succeeded'}
[ 2022-04-27T20:38:59     INFO ] [ get                      ] {'additional_properties': {}, 'id': '/subscriptions/b698965a-1f53-45ec-8b81-58458d1b25f7/resourceGroups/VMSSReImageRun1SOUTHCENTRALUS/providers/Microsoft.Network/virtualNetworks/vmssPeregrineTest-vnet', 'name': 'vmssPeregrineTest-vnet', 'type': 'Microsoft.Network/virtualNetworks', 'location': 'southcentralus', 'tags': {'confidentiality': 'public'}, 'extended_location': None, 'etag': 'W/"afdc11b6-3c43-4b31-b872-581f5fe7295f"', 'address_space': <azure.mgmt.network.v2021_05_01.models._models_py3.AddressSpace object at 0x7fc922f2d3d0>, 'dhcp_options': None, 'flow_timeout_in_minutes': None, 'subnets': [<azure.mgmt.network.v2021_05_01.models._models_py3.Subnet object at 0x7fc9235d61c0>], 'virtual_network_peerings': [], 'resource_guid': 'f9c58b12-e959-47a6-90a3-d01f242a9657', 'provisioning_state': 'Succeeded', 'enable_ddos_protection': False, 'enable_vm_protection': None, 'ddos_protection_plan': None, 'bgp_communities': None, 'encryption': None, 'ip_allocations': None}
[ 2022-04-27T20:38:59     INFO ] [ subnets_list             ] <iterator object azure.core.paging.ItemPaged at 0x7fc922f99c70>
[ 2022-04-27T20:39:01     INFO ] [ get                      ] {'additional_properties': {}, 'id': '/subscriptions/b698965a-1f53-45ec-8b81-58458d1b25f7/resourceGroups/VMSSReImageRun1SOUTHCENTRALUS/providers/Microsoft.Compute/virtualMachineScaleSets/vmssPeregrineTest', 'name': 'vmssPeregrineTest', 'type': 'Microsoft.Compute/virtualMachineScaleSets', 'location': 'southcentralus', 'tags': {'confidentiality': 'public'}, 'sku': <azure.mgmt.compute.v2021_11_01.models._models_py3.Sku object at 0x7fc922c90d00>, 'plan': None, 'identity': None, 'zones': ['1'], 'extended_location': None, 'upgrade_policy': None, 'automatic_repairs_policy': None, 'virtual_machine_profile': <azure.mgmt.compute.v2021_11_01.models._models_py3.VirtualMachineScaleSetVMProfile object at 0x7fc922ca1250>, 'provisioning_state': 'Succeeded', 'overprovision': None, 'do_not_run_extensions_on_overprovisioned_v_ms': None, 'unique_id': '8348e0b6-fe44-4f7e-81b3-a0dbaa7dfc36', 'single_placement_group': False, 'zone_balance': None, 'platform_fault_domain_count': 1, 'proximity_placement_group': None, 'host_group': None, 'additional_capabilities': None, 'scale_in_policy': None, 'orchestration_mode': 'Flexible', 'spot_restore_policy': None, 'time_created': datetime.datetime(2022, 4, 26, 16, 26, 1, 84949, tzinfo=<FixedOffset '+00:00'>)}
[ 2022-04-27T20:39:01     INFO ] [ get_vms                  ] <iterator object azure.core.paging.ItemPaged at 0x7fc922f58970>
[ 2022-04-27T20:39:01    DEBUG ] Using selector: EpollSelector
[ 2022-04-27T20:39:01     INFO ] [ get_vms                  ] <iterator object azure.core.paging.ItemPaged at 0x7fc922ca1e80>
[ 2022-04-27T20:39:01     INFO ] Finish queuing all vms
[ 2022-04-27T20:39:02     INFO ] [ get                      ] {'additional_properties': {}, 'platform_update_domain': None, 'platform_fault_domain': None, 'computer_name': 'vmInstance0H1VQ8', 'os_name': 'ubuntu', 'os_version': '18.04', 'hyper_v_generation': 'V1', 'rdp_thumb_print': None, 'vm_agent': <azure.mgmt.compute.v2021_11_01.models._models_py3.VirtualMachineAgentInstanceView object at 0x7fc922c52130>, 'maintenance_redeploy_status': None, 'disks': [<azure.mgmt.compute.v2021_11_01.models._models_py3.DiskInstanceView object at 0x7fc922c52310>], 'extensions': [], 'vm_health': None, 'boot_diagnostics': <azure.mgmt.compute.v2021_11_01.models._models_py3.BootDiagnosticsInstanceView object at 0x7fc922c521c0>, 'assigned_host': None, 'statuses': [<azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7fc922c52460>, <azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7fc922c52490>], 'patch_status': None}
[ 2022-04-27T20:39:03     INFO ] [ get                      ] {'additional_properties': {}, 'platform_update_domain': None, 'platform_fault_domain': None, 'computer_name': 'vmInstance0RB9YO', 'os_name': 'ubuntu', 'os_version': '18.04', 'hyper_v_generation': 'V1', 'rdp_thumb_print': None, 'vm_agent': <azure.mgmt.compute.v2021_11_01.models._models_py3.VirtualMachineAgentInstanceView object at 0x7fc921e50520>, 'maintenance_redeploy_status': None, 'disks': [<azure.mgmt.compute.v2021_11_01.models._models_py3.DiskInstanceView object at 0x7fc921e50700>], 'extensions': [], 'vm_health': None, 'boot_diagnostics': <azure.mgmt.compute.v2021_11_01.models._models_py3.BootDiagnosticsInstanceView object at 0x7fc921e505b0>, 'assigned_host': None, 'statuses': [<azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7fc921e50850>, <azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7fc921e50880>], 'patch_status': None}
[ 2022-04-27T20:39:03     INFO ] [ get                      ] {'additional_properties': {}, 'platform_update_domain': None, 'platform_fault_domain': None, 'computer_name': 'vmInstance3SYUES', 'os_name': 'ubuntu', 'os_version': '18.04', 'hyper_v_generation': 'V1', 'rdp_thumb_print': None, 'vm_agent': <azure.mgmt.compute.v2021_11_01.models._models_py3.VirtualMachineAgentInstanceView object at 0x7fc921e57910>, 'maintenance_redeploy_status': None, 'disks': [<azure.mgmt.compute.v2021_11_01.models._models_py3.DiskInstanceView object at 0x7fc921e57af0>], 'extensions': [], 'vm_health': None, 'boot_diagnostics': <azure.mgmt.compute.v2021_11_01.models._models_py3.BootDiagnosticsInstanceView object at 0x7fc921e579a0>, 'assigned_host': None, 'statuses': [<azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7fc921e57c40>, <azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7fc921e57c70>], 'patch_status': None}
[ 2022-04-27T20:39:04  WARNING ] AzureCliCredential.get_token failed: Unexpected output from Azure CLI: '--- Logging error ---
Traceback (most recent call last):
  File "/home/crodriguezde/.local/lib/python3.8/site-packages/azure/cli/__main__.py", line 60, in <module>
    raise ex
  File "/home/crodriguezde/.local/lib/python3.8/site-packages/azure/cli/__main__.py", line 53, in <module>
    sys.exit(exit_code)
SystemExit: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/handlers.py", line 70, in emit
    self.doRollover()
  File "/usr/lib/python3.8/logging/handlers.py", line 171, in doRollover
    self.rotate(self.baseFilename, dfn)
  File "/usr/lib/python3.8/logging/handlers.py", line 111, in rotate
    os.rename(source, dest)
FileNotFoundError: [Errno 2] No such file or directory: '/home/crodriguezde/.azure/telemetry/cache' -> '/home/crodriguezde/.azure/telemetry/cache.1'
Call stack:
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/crodriguezde/.local/lib/python3.8/site-packages/azure/cli/__main__.py", line 123, in <module>
    telemetry.conclude()
  File "/home/crodriguezde/.local/lib/python3.8/site-packages/azure/cli/core/telemetry.py", line 241, in _wrapper
    return func(*args, **kwargs)
  File "/home/crodriguezde/.local/lib/python3.8/site-packages/azure/cli/core/decorators.py", line 79, in _wrapped_func
    return func(*args, **kwargs)
  File "/home/crodriguezde/.local/lib/python3.8/site-packages/azure/cli/core/telemetry.py", line 297, in conclude
    save(get_config_dir(), _session.generate_payload())
  File "/home/crodriguezde/.local/lib/python3.8/site-packages/azure/cli/telemetry/__init__.py", line 51, in save
    if save_payload(config_dir, payload) and should_upload(config_dir):
  File "/home/crodriguezde/.local/lib/python3.8/site-packages/azure/cli/telemetry/util.py", line 53, in save_payload
    cache_saver.info(payload)
Message: '{"c4395b75-49cc-422c-bc95-c7d51aef5d46":[{"name":"azurecli/command","properties":{"Reserved.DataModel.EntityType":"UserTask","Reserved.DataModel.Action.Type":"Atomic","Reserved.DataModel.Action.Result":"Success","Reserved.ChannelUsed":"AI","Reserved.EventId":"93773857-0863-4945-8371-96d417454d6f","Reserved.SequenceNumber":1,"Reserved.SessionId":"f9b8a512f2f686b280965535b3fce02281bf4d343765c270c21e6a7915542a49","Reserved.TimeSinceSessionStart":0,"Reserved.DataModel.Source":"DataModelAPI","Reserved.DataModel.EntitySchemaVersion":4,"Reserved.DataModel.Severity":0,"Reserved.DataModel.ProductName":"azurecli","Reserved.DataModel.FeatureName":"command","Reserved.DataModel.EntityName":"account-getaccesstoken","Reserved.DataModel.CorrelationId":"3f0741dd-20bc-43dd-bf3c-6f74af8323c3","Context.Default.VS.Core.ExeName":"azurecli","Context.Default.VS.Core.ExeVersion":"2.35.0@none","Context.Default.VS.Core.MacAddressHash":"e9bfd1348393ff8f258c5b795e82bf541f4459c5b4d6fa911e34d480ac33d348","Context.Default.VS.Core.Machine.Id":"e9bfd134-8393-ff8f-258c-5b795e82bf54","Context.Default.VS.Core.OS.Type":"linux","Context.Default.VS.Core.OS.Version":"#1 smp wed mar 2 00:30:59 utc 2022","Context.Default.VS.Core.OS.Platform":"linux-5.10.102.1-microsoft-standard-wsl2-x86_64-with-glibc2.29","Context.Default.VS.Core.User.Id":"64c5b0af-e344-11eb-b316-c03c59895c0a","Context.Default.VS.Core.User.IsMicrosoftInternal":"False","Context.Default.VS.Core.User.IsOptedIn":"True","Context.Default.VS.Core.TelemetryApi.ProductVersion":"azurecli@2.35.0","Context.Default.AzureCLI.Source":"az","Context.Default.AzureCLI.ClientRequestId":"fc5f2702-c693-11ec-9f03-00155d785913","Context.Default.AzureCLI.CoreVersion":"2.35.0","Context.Default.AzureCLI.TelemetryVersion":"2.0","Context.Default.AzureCLI.InstallationId":"64c5b0af-e344-11eb-b316-c03c59895c0a","Context.Default.AzureCLI.ShellType":"/usr/bin/zsh","Context.Default.AzureCLI.UserAzureId":"39921e2f44771b3d76a90cf4cac837fdf8e646729bbbcbe017a174f2298b5c4c","Context.Default.AzureCLI.UserAzureSubscriptionId":"b698965a-1f53-45ec-8b81-58458d1b25f7","Context.Default.AzureCLI.DefaultOutputType":"unknown","Context.Default.AzureCLI.EnvironmentVariables":"[]","Context.Default.AzureCLI.Locale":"en_US,UTF-8","Context.Default.AzureCLI.StartTime":"2022-04-28 01:39:03.812384","Context.Default.AzureCLI.EndTime":"2022-04-28 01:39:03.982126","Context.Default.AzureCLI.InitTimeElapsed":"0.108809","Context.Default.AzureCLI.InvokeTimeElapsed":"0.167129","Context.Default.AzureCLI.OutputType":"json","Context.Default.AzureCLI.RawCommand":"account get-access-token","Context.Default.AzureCLI.Params":"--output,--resource","Context.Default.AzureCLI.PythonVersion":"3.8.10","Context.Default.AzureCLI.Mode":"default","Context.Default.AzureCLI.Installer":"PIP","Context.Default.AzureCLI.error_type":"None","Context.Default.AzureCLI.exception_name":"None","Context.Default.AzureCLI.debug_info":"","Context.Default.AzureCLI.PollStartTime":"None","Context.Default.AzureCLI.PollEndTime":"None"}}]}'
Arguments: ()
{
  ****,
  "expiresOn": "2022-04-27 20:58:30.000000",
  "subscription": "b698965a-1f53-45ec-8b81-58458d1b25f7",
  "tenant": "72f988bf-86f1-41af-91ab-2d7cd011db47",
  "tokenType": "Bearer"
}
'. 
To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/python/identity/azclicredential/troubleshoot.
[ 2022-04-27T20:39:04     INFO ] [ get                      ] {'additional_properties': {}, 'platform_update_domain': None, 'platform_fault_domain': None, 'computer_name': 'vmInstance53CLNL', 'os_name': 'ubuntu', 'os_version': '18.04', 'hyper_v_generation': 'V1', 'rdp_thumb_print': None, 'vm_agent': <azure.mgmt.compute.v2021_11_01.models._models_py3.VirtualMachineAgentInstanceView object at 0x7fc921e60bb0>, 'maintenance_redeploy_status': None, 'disks': [<azure.mgmt.compute.v2021_11_01.models._models_py3.DiskInstanceView object at 0x7fc921e60dc0>], 'extensions': [], 'vm_health': None, 'boot_diagnostics': <azure.mgmt.compute.v2021_11_01.models._models_py3.BootDiagnosticsInstanceView object at 0x7fc921e60e50>, 'assigned_host': None, 'statuses': [<azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7fc921e60c10>, <azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7fc921e60ac0>], 'patch_status': None}
[ 2022-04-27T20:39:05     INFO ] [ get                      ] {'additional_properties': {}, 'platform_update_domain': None, 'platform_fault_domain': None, 'computer_name': 'vmInstance5D58EP', 'os_name': 'ubuntu', 'os_version': '18.04', 'hyper_v_generation': 'V1', 'rdp_thumb_print': None, 'vm_agent': <azure.mgmt.compute.v2021_11_01.models._models_py3.VirtualMachineAgentInstanceView object at 0x7fc921e73130>, 'maintenance_redeploy_status': None, 'disks': [<azure.mgmt.compute.v2021_11_01.models._models_py3.DiskInstanceView object at 0x7fc921e73310>], 'extensions': [], 'vm_health': None, 'boot_diagnostics': <azure.mgmt.compute.v2021_11_01.models._models_py3.BootDiagnosticsInstanceView object at 0x7fc921e731c0>, 'assigned_host': None, 'statuses': [<azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7fc921e73460>, <azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7fc921e73490>], 'patch_status': None}
[ 2022-04-27T20:39:05     INFO ] [ get                      ] {'additional_properties': {}, 'platform_update_domain': None, 'platform_fault_domain': None, 'computer_name': 'vmInstance5K9YCQ', 'os_name': 'ubuntu', 'os_version': '18.04', 'hyper_v_generation': 'V1', 'rdp_thumb_print': None, 'vm_agent': <azure.mgmt.compute.v2021_11_01.models._models_py3.VirtualMachineAgentInstanceView object at 0x7fc9216036a0>, 'maintenance_redeploy_status': None, 'disks': [<azure.mgmt.compute.v2021_11_01.models._models_py3.DiskInstanceView object at 0x7fc921603880>], 'extensions': [], 'vm_health': None, 'boot_diagnostics': <azure.mgmt.compute.v2021_11_01.models._models_py3.BootDiagnosticsInstanceView object at 0x7fc921603730>, 'assigned_host': None, 'statuses': [<azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7fc9216039d0>, <azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7fc921603a00>], 'patch_status': None}
[ 2022-04-27T20:39:06     INFO ] [ get                      ] {'additional_properties': {}, 'platform_update_domain': None, 'platform_fault_domain': None, 'computer_name': 'vmInstance7JHJ5B', 'os_name': 'ubuntu', 'os_version': '18.04', 'hyper_v_generation': 'V1', 'rdp_thumb_print': None, 'vm_agent': <azure.mgmt.compute.v2021_11_01.models._models_py3.VirtualMachineAgentInstanceView object at 0x7fc921608970>, 'maintenance_redeploy_status': None, 'disks': [<azure.mgmt.compute.v2021_11_01.models._models_py3.DiskInstanceView object at 0x7fc921608b50>], 'extensions': [], 'vm_health': None, 'boot_diagnostics': <azure.mgmt.compute.v2021_11_01.models._models_py3.BootDiagnosticsInstanceView object at 0x7fc921608a00>, 'assigned_host': None, 'statuses': [<azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7fc921608ca0>, <azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7fc921608cd0>], 'patch_status': None}
[ 2022-04-27T20:39:06     INFO ] [ get                      ] {'additional_properties': {}, 'platform_update_domain': None, 'platform_fault_domain': None, 'computer_name': 'vmInstanceAA7RWS', 'os_name': 'ubuntu', 'os_version': '18.04', 'hyper_v_generation': 'V1', 'rdp_thumb_print': None, 'vm_agent': <azure.mgmt.compute.v2021_11_01.models._models_py3.VirtualMachineAgentInstanceView object at 0x7fc92160fee0>, 'maintenance_redeploy_status': None, 'disks': [<azure.mgmt.compute.v2021_11_01.models._models_py3.DiskInstanceView object at 0x7fc921618100>], 'extensions': [], 'vm_health': None, 'boot_diagnostics': <azure.mgmt.compute.v2021_11_01.models._models_py3.BootDiagnosticsInstanceView object at 0x7fc92160ff70>, 'assigned_host': None, 'statuses': [<azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7fc921618250>, <azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7fc921618280>], 'patch_status': None}
[ 2022-04-27T20:39:07     INFO ] [ get                      ] {'additional_properties': {}, 'platform_update_domain': None, 'platform_fault_domain': None, 'computer_name': 'vmInstanceB9R1NT', 'os_name': 'ubuntu', 'os_version': '18.04', 'hyper_v_generation': 'V1', 'rdp_thumb_print': None, 'vm_agent': <azure.mgmt.compute.v2021_11_01.models._models_py3.VirtualMachineAgentInstanceView object at 0x7fc921603df0>, 'maintenance_redeploy_status': None, 'disks': [<azure.mgmt.compute.v2021_11_01.models._models_py3.DiskInstanceView object at 0x7fc92161c430>], 'extensions': [], 'vm_health': None, 'boot_diagnostics': <azure.mgmt.compute.v2021_11_01.models._models_py3.BootDiagnosticsInstanceView object at 0x7fc92161c280>, 'assigned_host': None, 'statuses': [<azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7fc92161c580>, <azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7fc92161c5b0>], 'patch_status': None}
[ 2022-04-27T20:39:07     INFO ] Starting processing for vmssPeregrineTest_01b507e0
[ 2022-04-27T20:39:07     INFO ] Starting processing for vmssPeregrineTest_02bc0230
[ 2022-04-27T20:39:07     INFO ] Starting processing for vmssPeregrineTest_0db65674
[ 2022-04-27T20:39:07     INFO ] Starting processing for vmssPeregrineTest_125b0fa1
[ 2022-04-27T20:39:07     INFO ] Starting processing for vmssPeregrineTest_13561ad1
[ 2022-04-27T20:39:07     INFO ] Starting processing for vmssPeregrineTest_140cde2a
[ 2022-04-27T20:39:07     INFO ] Starting processing for vmssPeregrineTest_1b2dea2f
[ 2022-04-27T20:39:07     INFO ] Starting processing for vmssPeregrineTest_25103b0c
[ 2022-04-27T20:39:07     INFO ] Starting processing for vmssPeregrineTest_289ef629
[ 2022-04-27T20:39:07     INFO ] AzureCliCredential.get_token succeeded
[ 2022-04-27T20:39:07    DEBUG ] [Authenticated account] Client ID: 04b07795-8ddb-461a-bbee-02f9e1bf7b46. Tenant ID: 72f988bf-86f1-41af-91ab-2d7cd011db47. User Principal Name: crodriguezde@microsoft.com. Object ID (user): ab969cee-6fd6-4809-91a9-6e3e7aafe6c2
[ 2022-04-27T20:39:07     INFO ] AzureCliCredential.get_token succeeded
[ 2022-04-27T20:39:07    DEBUG ] [Authenticated account] Client ID: 04b07795-8ddb-461a-bbee-02f9e1bf7b46. Tenant ID: 72f988bf-86f1-41af-91ab-2d7cd011db47. User Principal Name: crodriguezde@microsoft.com. Object ID (user): ab969cee-6fd6-4809-91a9-6e3e7aafe6c2
[ 2022-04-27T20:39:07     INFO ] AzureCliCredential.get_token succeeded
[ 2022-04-27T20:39:07    DEBUG ] [Authenticated account] Client ID: 04b07795-8ddb-461a-bbee-02f9e1bf7b46. Tenant ID: 72f988bf-86f1-41af-91ab-2d7cd011db47. User Principal Name: crodriguezde@microsoft.com. Object ID (user): ab969cee-6fd6-4809-91a9-6e3e7aafe6c2
[ 2022-04-27T20:39:07     INFO ] AzureCliCredential.get_token succeeded
[ 2022-04-27T20:39:07    DEBUG ] [Authenticated account] Client ID: 04b07795-8ddb-461a-bbee-02f9e1bf7b46. Tenant ID: 72f988bf-86f1-41af-91ab-2d7cd011db47. User Principal Name: crodriguezde@microsoft.com. Object ID (user): ab969cee-6fd6-4809-91a9-6e3e7aafe6c2
[ 2022-04-27T20:39:07     INFO ] AzureCliCredential.get_token succeeded
[ 2022-04-27T20:39:07    DEBUG ] [Authenticated account] Client ID: 04b07795-8ddb-461a-bbee-02f9e1bf7b46. Tenant ID: 72f988bf-86f1-41af-91ab-2d7cd011db47. User Principal Name: crodriguezde@microsoft.com. Object ID (user): ab969cee-6fd6-4809-91a9-6e3e7aafe6c2
[ 2022-04-27T20:39:07     INFO ] AzureCliCredential.get_token succeeded
[ 2022-04-27T20:39:07    DEBUG ] [Authenticated account] Client ID: 04b07795-8ddb-461a-bbee-02f9e1bf7b46. Tenant ID: 72f988bf-86f1-41af-91ab-2d7cd011db47. User Principal Name: crodriguezde@microsoft.com. Object ID (user): ab969cee-6fd6-4809-91a9-6e3e7aafe6c2
[ 2022-04-27T20:39:07     INFO ] AzureCliCredential.get_token succeeded
[ 2022-04-27T20:39:07    DEBUG ] [Authenticated account] Client ID: 04b07795-8ddb-461a-bbee-02f9e1bf7b46. Tenant ID: 72f988bf-86f1-41af-91ab-2d7cd011db47. User Principal Name: crodriguezde@microsoft.com. Object ID (user): ab969cee-6fd6-4809-91a9-6e3e7aafe6c2
[ 2022-04-27T20:39:07     INFO ] AzureCliCredential.get_token succeeded
[ 2022-04-27T20:39:07    DEBUG ] [Authenticated account] Client ID: 04b07795-8ddb-461a-bbee-02f9e1bf7b46. Tenant ID: 72f988bf-86f1-41af-91ab-2d7cd011db47. User Principal Name: crodriguezde@microsoft.com. Object ID (user): ab969cee-6fd6-4809-91a9-6e3e7aafe6c2
[ 2022-04-27T20:39:07    DEBUG ] Encoding detection on empty bytes, assuming utf_8 intention.
[ 2022-04-27T20:39:07    DEBUG ] Encoding detection on empty bytes, assuming utf_8 intention.
[ 2022-04-27T20:39:07    DEBUG ] Encoding detection on empty bytes, assuming utf_8 intention.
[ 2022-04-27T20:39:07    DEBUG ] Encoding detection on empty bytes, assuming utf_8 intention.
[ 2022-04-27T20:39:07    DEBUG ] Encoding detection on empty bytes, assuming utf_8 intention.
[ 2022-04-27T20:39:07     INFO ] AzureCliCredential.get_token succeeded
[ 2022-04-27T20:39:07    DEBUG ] [Authenticated account] Client ID: 04b07795-8ddb-461a-bbee-02f9e1bf7b46. Tenant ID: 72f988bf-86f1-41af-91ab-2d7cd011db47. User Principal Name: crodriguezde@microsoft.com. Object ID (user): ab969cee-6fd6-4809-91a9-6e3e7aafe6c2
[ 2022-04-27T20:39:07    DEBUG ] Encoding detection on empty bytes, assuming utf_8 intention.
[ 2022-04-27T20:39:07    DEBUG ] Encoding detection on empty bytes, assuming utf_8 intention.
[ 2022-04-27T20:39:07    DEBUG ] Encoding detection on empty bytes, assuming utf_8 intention.
[ 2022-04-27T20:39:08    DEBUG ] Encoding detection on empty bytes, assuming utf_8 intention.
[ 2022-04-27T21:48:56    ERROR ] Task exception was never retrieved
future: <Task finished name='Task-11' coro=<_get() done, defined at /home/crodriguezde/experiments/reimage/imds.py:20> exception=AttributeError("'Queue' object has no attribute 'put_noawait'")>
Traceback (most recent call last):
  File "/home/crodriguezde/experiments/reimage/imds.py", line 43, in _get
    log_queue.put_noawait(imds)
AttributeError: 'Queue' object has no attribute 'put_noawait'
[ 2022-04-27T21:48:56    ERROR ] Task exception was never retrieved
future: <Task finished name='Task-10' coro=<_get() done, defined at /home/crodriguezde/experiments/reimage/imds.py:20> exception=AttributeError("'Queue' object has no attribute 'put_noawait'")>
Traceback (most recent call last):
  File "/home/crodriguezde/experiments/reimage/imds.py", line 43, in _get
    log_queue.put_noawait(imds)
AttributeError: 'Queue' object has no attribute 'put_noawait'
[ 2022-04-27T21:48:56    ERROR ] Task exception was never retrieved
future: <Task finished name='Task-9' coro=<_get() done, defined at /home/crodriguezde/experiments/reimage/imds.py:20> exception=AttributeError("'Queue' object has no attribute 'put_noawait'")>
Traceback (most recent call last):
  File "/home/crodriguezde/experiments/reimage/imds.py", line 43, in _get
    log_queue.put_noawait(imds)
AttributeError: 'Queue' object has no attribute 'put_noawait'
[ 2022-04-27T21:48:56    ERROR ] Task exception was never retrieved
future: <Task finished name='Task-8' coro=<_get() done, defined at /home/crodriguezde/experiments/reimage/imds.py:20> exception=AttributeError("'Queue' object has no attribute 'put_noawait'")>
Traceback (most recent call last):
  File "/home/crodriguezde/experiments/reimage/imds.py", line 43, in _get
    log_queue.put_noawait(imds)
AttributeError: 'Queue' object has no attribute 'put_noawait'
[ 2022-04-27T21:48:56    ERROR ] Task exception was never retrieved
future: <Task finished name='Task-7' coro=<_get() done, defined at /home/crodriguezde/experiments/reimage/imds.py:20> exception=AttributeError("'Queue' object has no attribute 'put_noawait'")>
Traceback (most recent call last):
  File "/home/crodriguezde/experiments/reimage/imds.py", line 43, in _get
    log_queue.put_noawait(imds)
AttributeError: 'Queue' object has no attribute 'put_noawait'
[ 2022-04-27T21:48:56    ERROR ] Task exception was never retrieved
future: <Task finished name='Task-6' coro=<_get() done, defined at /home/crodriguezde/experiments/reimage/imds.py:20> exception=ClientAuthenticationError('Unexpected output from Azure CLI: \'--- Logging error ---\nTraceback (most recent call last):\n  File "/home/crodriguezde/.local/lib/python3.8/site-packages/azure/cli/__main__.py", line 60, in <module>\n    raise ex\n  File "/home/crodriguezde/.local/lib/python3.8/site-packages/azure/cli/__main__.py", line 53, in <module>\n    sys.exit(exit_code)\nSystemExit: 0\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/usr/lib/python3.8/logging/handlers.py", line 70, in emit\n    self.doRollover()\n  File "/usr/lib/python3.8/logging/handlers.py", line 171, in doRollover\n    self.rotate(self.baseFilename, dfn)\n  File "/usr/lib/python3.8/logging/handlers.py", line 111, in rotate\n    os.rename(source, dest)\nFileNotFoundError: [Errno 2] No such file or directory: \'/home/crodriguezde/.azure/telemetry/cache\' -> \'/home/crodriguezde/.azure/telemetry/cache.1\'\nCall stack:\n  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main\n    return _run_code(code, main_globals, None,\n  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code\n    exec(code, run_globals)\n  File "/home/crodriguezde/.local/lib/python3.8/site-packages/azure/cli/__main__.py", line 123, in <module>\n    telemetry.conclude()\n  File "/home/crodriguezde/.local/lib/python3.8/site-packages/azure/cli/core/telemetry.py", line 241, in _wrapper\n    return func(*args, **kwargs)\n  File "/home/crodriguezde/.local/lib/python3.8/site-packages/azure/cli/core/decorators.py", line 79, in _wrapped_func\n    return func(*args, **kwargs)\n  File "/home/crodriguezde/.local/lib/python3.8/site-packages/azure/cli/core/telemetry.py", line 297, in conclude\n    save(get_config_dir(), _session.generate_payload())\n  File "/home/crodriguezde/.local/lib/python3.8/site-packages/azure/cli/telemetry/__init__.py", line 51, in save\n    if save_payload(config_dir, payload) and should_upload(config_dir):\n  File "/home/crodriguezde/.local/lib/python3.8/site-packages/azure/cli/telemetry/util.py", line 53, in save_payload\n    cache_saver.info(payload)\nMessage: \'{"c4395b75-49cc-422c-bc95-c7d51aef5d46":[{"name":"azurecli/command","properties":{"Reserved.DataModel.EntityType":"UserTask","Reserved.DataModel.Action.Type":"Atomic","Reserved.DataModel.Action.Result":"Success","Reserved.ChannelUsed":"AI","Reserved.EventId":"93773857-0863-4945-8371-96d417454d6f","Reserved.SequenceNumber":1,"Reserved.SessionId":"f9b8a512f2f686b280965535b3fce02281bf4d343765c270c21e6a7915542a49","Reserved.TimeSinceSessionStart":0,"Reserved.DataModel.Source":"DataModelAPI","Reserved.DataModel.EntitySchemaVersion":4,"Reserved.DataModel.Severity":0,"Reserved.DataModel.ProductName":"azurecli","Reserved.DataModel.FeatureName":"command","Reserved.DataModel.EntityName":"account-getaccesstoken","Reserved.DataModel.CorrelationId":"3f0741dd-20bc-43dd-bf3c-6f74af8323c3","Context.Default.VS.Core.ExeName":"azurecli","Context.Default.VS.Core.ExeVersion":"2.35.0@none","Context.Default.VS.Core.MacAddressHash":"e9bfd1348393ff8f258c5b795e82bf541f4459c5b4d6fa911e34d480ac33d348","Context.Default.VS.Core.Machine.Id":"e9bfd134-8393-ff8f-258c-5b795e82bf54","Context.Default.VS.Core.OS.Type":"linux","Context.Default.VS.Core.OS.Version":"#1 smp wed mar 2 00:30:59 utc 2022","Context.Default.VS.Core.OS.Platform":"linux-5.10.102.1-microsoft-standard-wsl2-x86_64-with-glibc2.29","Context.Default.VS.Core.User.Id":"64c5b0af-e344-11eb-b316-c03c59895c0a","Context.Default.VS.Core.User.IsMicrosoftInternal":"False","Context.Default.VS.Core.User.IsOptedIn":"True","Context.Default.VS.Core.TelemetryApi.ProductVersion":"azurecli@2.35.0","Context.Default.AzureCLI.Source":"az","Context.Default.AzureCLI.ClientRequestId":"fc5f2702-c693-11ec-9f03-00155d785913","Context.Default.AzureCLI.CoreVersion":"2.35.0","Context.Default.AzureCLI.TelemetryVersion":"2.0","Context.Default.AzureCLI.InstallationId":"64c5b0af-e344-11eb-b316-c03c59895c0a","Context.Default.AzureCLI.ShellType":"/usr/bin/zsh","Context.Default.AzureCLI.UserAzureId":"39921e2f44771b3d76a90cf4cac837fdf8e646729bbbcbe017a174f2298b5c4c","Context.Default.AzureCLI.UserAzureSubscriptionId":"b698965a-1f53-45ec-8b81-58458d1b25f7","Context.Default.AzureCLI.DefaultOutputType":"unknown","Context.Default.AzureCLI.EnvironmentVariables":"[]","Context.Default.AzureCLI.Locale":"en_US,UTF-8","Context.Default.AzureCLI.StartTime":"2022-04-28 01:39:03.812384","Context.Default.AzureCLI.EndTime":"2022-04-28 01:39:03.982126","Context.Default.AzureCLI.InitTimeElapsed":"0.108809","Context.Default.AzureCLI.InvokeTimeElapsed":"0.167129","Context.Default.AzureCLI.OutputType":"json","Context.Default.AzureCLI.RawCommand":"account get-access-token","Context.Default.AzureCLI.Params":"--output,--resource","Context.Default.AzureCLI.PythonVersion":"3.8.10","Context.Default.AzureCLI.Mode":"default","Context.Default.AzureCLI.Installer":"PIP","Context.Default.AzureCLI.error_type":"None","Context.Default.AzureCLI.exception_name":"None","Context.Default.AzureCLI.debug_info":"","Context.Default.AzureCLI.PollStartTime":"None","Context.Default.AzureCLI.PollEndTime":"None"}}]}\'\nArguments: ()\n{\n  ****,\n  "expiresOn": "2022-04-27 20:58:30.000000",\n  "subscription": "b698965a-1f53-45ec-8b81-58458d1b25f7",\n  "tenant": "72f988bf-86f1-41af-91ab-2d7cd011db47",\n  "tokenType": "Bearer"\n}\n\'. \nTo mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/python/identity/azclicredential/troubleshoot.')>
Traceback (most recent call last):
  File "/home/crodriguezde/experiments/reimage/imds.py", line 23, in _get
    instance_vm = _wait_vm_state_running(cli_args, vmss_vm)
  File "/home/crodriguezde/experiments/reimage/venv/lib/python3.8/site-packages/backoff/_sync.py", line 43, in retry
    ret = target(*args, **kwargs)
  File "/home/crodriguezde/experiments/reimage/imds.py", line 50, in _wait_vm_state_running
    instance_vm = vm.get(args, vmss_vm)
  File "/home/crodriguezde/experiments/reimage/utils.py", line 13, in timer
    result = fn(*args, **kwargs)
  File "/home/crodriguezde/experiments/reimage/vm.py", line 31, in get
    return resource_client.virtual_machines.instance_view(
  File "/home/crodriguezde/experiments/reimage/venv/lib/python3.8/site-packages/azure/core/tracing/decorator.py", line 73, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/home/crodriguezde/experiments/reimage/venv/lib/python3.8/site-packages/azure/mgmt/compute/v2021_11_01/operations/_virtual_machines_operations.py", line 1626, in instance_view
    pipeline_response = self._client._pipeline.run(request, stream=False, **kwargs)
  File "/home/crodriguezde/experiments/reimage/venv/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 211, in run
    return first_node.send(pipeline_request)  # type: ignore
  File "/home/crodriguezde/experiments/reimage/venv/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/home/crodriguezde/experiments/reimage/venv/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/home/crodriguezde/experiments/reimage/venv/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  [Previous line repeated 2 more times]
  File "/home/crodriguezde/experiments/reimage/venv/lib/python3.8/site-packages/azure/mgmt/core/policies/_base.py", line 47, in send
    response = self.next.send(request)
  File "/home/crodriguezde/experiments/reimage/venv/lib/python3.8/site-packages/azure/core/pipeline/policies/_redirect.py", line 158, in send
    response = self.next.send(request)
  File "/home/crodriguezde/experiments/reimage/venv/lib/python3.8/site-packages/azure/core/pipeline/policies/_retry.py", line 445, in send
    response = self.next.send(request)
  File "/home/crodriguezde/experiments/reimage/venv/lib/python3.8/site-packages/azure/core/pipeline/policies/_authentication.py", line 117, in send
    self.on_request(request)
  File "/home/crodriguezde/experiments/reimage/venv/lib/python3.8/site-packages/azure/core/pipeline/policies/_authentication.py", line 94, in on_request
    self._token = self._credential.get_token(*self._scopes)
  File "/home/crodriguezde/experiments/reimage/venv/lib/python3.8/site-packages/azure/identity/_internal/decorators.py", line 32, in wrapper
    token = fn(*args, **kwargs)
  File "/home/crodriguezde/experiments/reimage/venv/lib/python3.8/site-packages/azure/identity/_credentials/azure_cli.py", line 78, in get_token
    raise ClientAuthenticationError(
azure.core.exceptions.ClientAuthenticationError: Unexpected output from Azure CLI: '--- Logging error ---
Traceback (most recent call last):
  File "/home/crodriguezde/.local/lib/python3.8/site-packages/azure/cli/__main__.py", line 60, in <module>
    raise ex
  File "/home/crodriguezde/.local/lib/python3.8/site-packages/azure/cli/__main__.py", line 53, in <module>
    sys.exit(exit_code)
SystemExit: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/handlers.py", line 70, in emit
    self.doRollover()
  File "/usr/lib/python3.8/logging/handlers.py", line 171, in doRollover
    self.rotate(self.baseFilename, dfn)
  File "/usr/lib/python3.8/logging/handlers.py", line 111, in rotate
    os.rename(source, dest)
FileNotFoundError: [Errno 2] No such file or directory: '/home/crodriguezde/.azure/telemetry/cache' -> '/home/crodriguezde/.azure/telemetry/cache.1'
Call stack:
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/crodriguezde/.local/lib/python3.8/site-packages/azure/cli/__main__.py", line 123, in <module>
    telemetry.conclude()
  File "/home/crodriguezde/.local/lib/python3.8/site-packages/azure/cli/core/telemetry.py", line 241, in _wrapper
    return func(*args, **kwargs)
  File "/home/crodriguezde/.local/lib/python3.8/site-packages/azure/cli/core/decorators.py", line 79, in _wrapped_func
    return func(*args, **kwargs)
  File "/home/crodriguezde/.local/lib/python3.8/site-packages/azure/cli/core/telemetry.py", line 297, in conclude
    save(get_config_dir(), _session.generate_payload())
  File "/home/crodriguezde/.local/lib/python3.8/site-packages/azure/cli/telemetry/__init__.py", line 51, in save
    if save_payload(config_dir, payload) and should_upload(config_dir):
  File "/home/crodriguezde/.local/lib/python3.8/site-packages/azure/cli/telemetry/util.py", line 53, in save_payload
    cache_saver.info(payload)
Message: '{"c4395b75-49cc-422c-bc95-c7d51aef5d46":[{"name":"azurecli/command","properties":{"Reserved.DataModel.EntityType":"UserTask","Reserved.DataModel.Action.Type":"Atomic","Reserved.DataModel.Action.Result":"Success","Reserved.ChannelUsed":"AI","Reserved.EventId":"93773857-0863-4945-8371-96d417454d6f","Reserved.SequenceNumber":1,"Reserved.SessionId":"f9b8a512f2f686b280965535b3fce02281bf4d343765c270c21e6a7915542a49","Reserved.TimeSinceSessionStart":0,"Reserved.DataModel.Source":"DataModelAPI","Reserved.DataModel.EntitySchemaVersion":4,"Reserved.DataModel.Severity":0,"Reserved.DataModel.ProductName":"azurecli","Reserved.DataModel.FeatureName":"command","Reserved.DataModel.EntityName":"account-getaccesstoken","Reserved.DataModel.CorrelationId":"3f0741dd-20bc-43dd-bf3c-6f74af8323c3","Context.Default.VS.Core.ExeName":"azurecli","Context.Default.VS.Core.ExeVersion":"2.35.0@none","Context.Default.VS.Core.MacAddressHash":"e9bfd1348393ff8f258c5b795e82bf541f4459c5b4d6fa911e34d480ac33d348","Context.Default.VS.Core.Machine.Id":"e9bfd134-8393-ff8f-258c-5b795e82bf54","Context.Default.VS.Core.OS.Type":"linux","Context.Default.VS.Core.OS.Version":"#1 smp wed mar 2 00:30:59 utc 2022","Context.Default.VS.Core.OS.Platform":"linux-5.10.102.1-microsoft-standard-wsl2-x86_64-with-glibc2.29","Context.Default.VS.Core.User.Id":"64c5b0af-e344-11eb-b316-c03c59895c0a","Context.Default.VS.Core.User.IsMicrosoftInternal":"False","Context.Default.VS.Core.User.IsOptedIn":"True","Context.Default.VS.Core.TelemetryApi.ProductVersion":"azurecli@2.35.0","Context.Default.AzureCLI.Source":"az","Context.Default.AzureCLI.ClientRequestId":"fc5f2702-c693-11ec-9f03-00155d785913","Context.Default.AzureCLI.CoreVersion":"2.35.0","Context.Default.AzureCLI.TelemetryVersion":"2.0","Context.Default.AzureCLI.InstallationId":"64c5b0af-e344-11eb-b316-c03c59895c0a","Context.Default.AzureCLI.ShellType":"/usr/bin/zsh","Context.Default.AzureCLI.UserAzureId":"39921e2f44771b3d76a90cf4cac837fdf8e646729bbbcbe017a174f2298b5c4c","Context.Default.AzureCLI.UserAzureSubscriptionId":"b698965a-1f53-45ec-8b81-58458d1b25f7","Context.Default.AzureCLI.DefaultOutputType":"unknown","Context.Default.AzureCLI.EnvironmentVariables":"[]","Context.Default.AzureCLI.Locale":"en_US,UTF-8","Context.Default.AzureCLI.StartTime":"2022-04-28 01:39:03.812384","Context.Default.AzureCLI.EndTime":"2022-04-28 01:39:03.982126","Context.Default.AzureCLI.InitTimeElapsed":"0.108809","Context.Default.AzureCLI.InvokeTimeElapsed":"0.167129","Context.Default.AzureCLI.OutputType":"json","Context.Default.AzureCLI.RawCommand":"account get-access-token","Context.Default.AzureCLI.Params":"--output,--resource","Context.Default.AzureCLI.PythonVersion":"3.8.10","Context.Default.AzureCLI.Mode":"default","Context.Default.AzureCLI.Installer":"PIP","Context.Default.AzureCLI.error_type":"None","Context.Default.AzureCLI.exception_name":"None","Context.Default.AzureCLI.debug_info":"","Context.Default.AzureCLI.PollStartTime":"None","Context.Default.AzureCLI.PollEndTime":"None"}}]}'
Arguments: ()
{
  ****,
  "expiresOn": "2022-04-27 20:58:30.000000",
  "subscription": "b698965a-1f53-45ec-8b81-58458d1b25f7",
  "tenant": "72f988bf-86f1-41af-91ab-2d7cd011db47",
  "tokenType": "Bearer"
}
'. 
To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/python/identity/azclicredential/troubleshoot.
[ 2022-04-27T21:48:56    ERROR ] Task exception was never retrieved
future: <Task finished name='Task-5' coro=<_get() done, defined at /home/crodriguezde/experiments/reimage/imds.py:20> exception=AttributeError("'Queue' object has no attribute 'put_noawait'")>
Traceback (most recent call last):
  File "/home/crodriguezde/experiments/reimage/imds.py", line 43, in _get
    log_queue.put_noawait(imds)
AttributeError: 'Queue' object has no attribute 'put_noawait'
[ 2022-04-27T21:48:56    ERROR ] Task exception was never retrieved
future: <Task finished name='Task-4' coro=<_get() done, defined at /home/crodriguezde/experiments/reimage/imds.py:20> exception=AttributeError("'Queue' object has no attribute 'put_noawait'")>
Traceback (most recent call last):
  File "/home/crodriguezde/experiments/reimage/imds.py", line 43, in _get
    log_queue.put_noawait(imds)
AttributeError: 'Queue' object has no attribute 'put_noawait'
[ 2022-04-27T21:48:56    ERROR ] Task exception was never retrieved
future: <Task finished name='Task-3' coro=<_get() done, defined at /home/crodriguezde/experiments/reimage/imds.py:20> exception=AttributeError("'Queue' object has no attribute 'put_noawait'")>
Traceback (most recent call last):
  File "/home/crodriguezde/experiments/reimage/imds.py", line 43, in _get
    log_queue.put_noawait(imds)
AttributeError: 'Queue' object has no attribute 'put_noawait'
[ 2022-04-27T21:48:56    ERROR ] Task exception was never retrieved
future: <Task finished name='Task-12' coro=<_get() done, defined at /home/crodriguezde/experiments/reimage/imds.py:20> exception=AttributeError("'Queue' object has no attribute 'put_noawait'")>
Traceback (most recent call last):
  File "/home/crodriguezde/experiments/reimage/imds.py", line 43, in _get
    log_queue.put_noawait(imds)
AttributeError: 'Queue' object has no attribute 'put_noawait'
[ 2022-04-27T21:48:56     INFO ] Exit per user request
[ 2022-04-27T21:48:57    ERROR ] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fc92160f0d0>
