[ 2022-04-27T20:03:00     INFO ] logging to applications insights
[ 2022-04-27T20:03:00     INFO ] [ exists                   ] True
[ 2022-04-27T20:03:02     INFO ] [ get                      ] {'additional_properties': {}, 'id': '/subscriptions/b698965a-1f53-45ec-8b81-58458d1b25f7/resourceGroups/VMSSReImageRun1SOUTHCENTRALUS', 'name': 'VMSSReImageRun1SOUTHCENTRALUS', 'type': 'Microsoft.Resources/resourceGroups', 'properties': <azure.mgmt.resource.resources.v2021_04_01.models._models_py3.ResourceGroupProperties object at 0x7f61966f1400>, 'location': 'southcentralus', 'managed_by': None, 'tags': None}
[ 2022-04-27T20:03:07     INFO ] [ create                   ] {'additional_properties': {}, 'id': '/subscriptions/b698965a-1f53-45ec-8b81-58458d1b25f7/resourceGroups/VMSSReImageRun1SOUTHCENTRALUS/providers/Microsoft.Storage/storageAccounts/vmsspipeline9fc2a6bc', 'name': 'vmsspipeline9fc2a6bc', 'type': 'Microsoft.Storage/storageAccounts', 'tags': {'confidentiality': 'public'}, 'location': 'southcentralus', 'sku': <azure.mgmt.storage.v2021_09_01.models._models_py3.Sku object at 0x7f6196514d90>, 'kind': 'StorageV2', 'identity': None, 'extended_location': None, 'provisioning_state': 'Succeeded', 'primary_endpoints': <azure.mgmt.storage.v2021_09_01.models._models_py3.Endpoints object at 0x7f6196514af0>, 'primary_location': 'southcentralus', 'status_of_primary': 'available', 'last_geo_failover_time': None, 'secondary_location': None, 'status_of_secondary': None, 'creation_time': datetime.datetime(2022, 4, 26, 16, 3, 34, 184382, tzinfo=<isodate.tzinfo.Utc object at 0x7f619e269610>), 'custom_domain': None, 'sas_policy': None, 'key_policy': None, 'key_creation_time': <azure.mgmt.storage.v2021_09_01.models._models_py3.KeyCreationTime object at 0x7f6196522070>, 'secondary_endpoints': None, 'encryption': <azure.mgmt.storage.v2021_09_01.models._models_py3.Encryption object at 0x7f6196522340>, 'access_tier': 'Hot', 'azure_files_identity_based_authentication': None, 'enable_https_traffic_only': True, 'network_rule_set': <azure.mgmt.storage.v2021_09_01.models._models_py3.NetworkRuleSet object at 0x7f61965225e0>, 'is_sftp_enabled': None, 'is_local_user_enabled': None, 'is_hns_enabled': None, 'geo_replication_stats': None, 'failover_in_progress': None, 'large_file_shares_state': None, 'private_endpoint_connections': [], 'routing_preference': None, 'blob_restore_status': None, 'allow_blob_public_access': True, 'minimum_tls_version': 'TLS1_0', 'allow_shared_key_access': None, 'enable_nfs_v3': None, 'allow_cross_tenant_replication': None, 'default_to_o_auth_authentication': None, 'public_network_access': None, 'immutable_storage_with_versioning': None, 'allowed_copy_scope': None, 'storage_account_sku_conversion_status': None, 'dns_endpoint_type': None}
[ 2022-04-27T20:03:08     INFO ] [ get                      ] {'additional_properties': {}, 'id': '/subscriptions/b698965a-1f53-45ec-8b81-58458d1b25f7/resourceGroups/VMSSReImageRun1SOUTHCENTRALUS/providers/Microsoft.Network/networkSecurityGroups/vmssPeregrineTest-nsg', 'name': 'vmssPeregrineTest-nsg', 'type': 'Microsoft.Network/networkSecurityGroups', 'location': 'southcentralus', 'tags': {'confidentiality': 'public'}, 'etag': 'W/"032dcc53-bfb9-4cda-95f8-9d8fe45e7237"', 'security_rules': [<azure.mgmt.network.v2021_05_01.models._models_py3.SecurityRule object at 0x7f6195e6a160>], 'default_security_rules': [<azure.mgmt.network.v2021_05_01.models._models_py3.SecurityRule object at 0x7f6195e6a070>, <azure.mgmt.network.v2021_05_01.models._models_py3.SecurityRule object at 0x7f6195e6a190>, <azure.mgmt.network.v2021_05_01.models._models_py3.SecurityRule object at 0x7f6195e6a1c0>, <azure.mgmt.network.v2021_05_01.models._models_py3.SecurityRule object at 0x7f6195e6a1f0>, <azure.mgmt.network.v2021_05_01.models._models_py3.SecurityRule object at 0x7f6195e6a220>, <azure.mgmt.network.v2021_05_01.models._models_py3.SecurityRule object at 0x7f6195e6a250>], 'network_interfaces': None, 'subnets': [<azure.mgmt.network.v2021_05_01.models._models_py3.Subnet object at 0x7f6195e6a2b0>], 'flow_logs': None, 'resource_guid': '203bc10e-1f08-45fe-8574-0dda31091c3d', 'provisioning_state': 'Succeeded'}
[ 2022-04-27T20:03:09     INFO ] [ get                      ] {'additional_properties': {}, 'id': '/subscriptions/b698965a-1f53-45ec-8b81-58458d1b25f7/resourceGroups/VMSSReImageRun1SOUTHCENTRALUS/providers/Microsoft.Network/virtualNetworks/vmssPeregrineTest-vnet', 'name': 'vmssPeregrineTest-vnet', 'type': 'Microsoft.Network/virtualNetworks', 'location': 'southcentralus', 'tags': {'confidentiality': 'public'}, 'extended_location': None, 'etag': 'W/"afdc11b6-3c43-4b31-b872-581f5fe7295f"', 'address_space': <azure.mgmt.network.v2021_05_01.models._models_py3.AddressSpace object at 0x7f6195e6a3d0>, 'dhcp_options': None, 'flow_timeout_in_minutes': None, 'subnets': [<azure.mgmt.network.v2021_05_01.models._models_py3.Subnet object at 0x7f61965141c0>], 'virtual_network_peerings': [], 'resource_guid': 'f9c58b12-e959-47a6-90a3-d01f242a9657', 'provisioning_state': 'Succeeded', 'enable_ddos_protection': False, 'enable_vm_protection': None, 'ddos_protection_plan': None, 'bgp_communities': None, 'encryption': None, 'ip_allocations': None}
[ 2022-04-27T20:03:09     INFO ] [ subnets_list             ] <iterator object azure.core.paging.ItemPaged at 0x7f6195ed6c70>
[ 2022-04-27T20:03:10     INFO ] [ get                      ] {'additional_properties': {}, 'id': '/subscriptions/b698965a-1f53-45ec-8b81-58458d1b25f7/resourceGroups/VMSSReImageRun1SOUTHCENTRALUS/providers/Microsoft.Compute/virtualMachineScaleSets/vmssPeregrineTest', 'name': 'vmssPeregrineTest', 'type': 'Microsoft.Compute/virtualMachineScaleSets', 'location': 'southcentralus', 'tags': {'confidentiality': 'public'}, 'sku': <azure.mgmt.compute.v2021_11_01.models._models_py3.Sku object at 0x7f6195e84b80>, 'plan': None, 'identity': None, 'zones': ['1'], 'extended_location': None, 'upgrade_policy': None, 'automatic_repairs_policy': None, 'virtual_machine_profile': <azure.mgmt.compute.v2021_11_01.models._models_py3.VirtualMachineScaleSetVMProfile object at 0x7f6195b61280>, 'provisioning_state': 'Succeeded', 'overprovision': None, 'do_not_run_extensions_on_overprovisioned_v_ms': None, 'unique_id': '8348e0b6-fe44-4f7e-81b3-a0dbaa7dfc36', 'single_placement_group': False, 'zone_balance': None, 'platform_fault_domain_count': 1, 'proximity_placement_group': None, 'host_group': None, 'additional_capabilities': None, 'scale_in_policy': None, 'orchestration_mode': 'Flexible', 'spot_restore_policy': None, 'time_created': datetime.datetime(2022, 4, 26, 16, 26, 1, 84949, tzinfo=<FixedOffset '+00:00'>)}
[ 2022-04-27T20:03:10     INFO ] [ get_vms                  ] <iterator object azure.core.paging.ItemPaged at 0x7f6195e84e50>
[ 2022-04-27T20:03:10     INFO ] [ get_from_vmss_vms        ] <coroutine object get_from_vmss_vms at 0x7f619d5b24c0>
[ 2022-04-27T20:03:10    DEBUG ] Using selector: EpollSelector
[ 2022-04-27T20:03:10     INFO ] [ get_vms                  ] <iterator object azure.core.paging.ItemPaged at 0x7f6195b61e20>
[ 2022-04-27T20:03:11     INFO ] Finish queuing all vms
[ 2022-04-27T20:03:50    ERROR ] Task exception was never retrieved
future: <Task finished name='Task-10' coro=<_get() done, defined at /home/crodriguezde/experiments/reimage/imds.py:14> exception=NameError("name 'args' is not defined")>
Traceback (most recent call last):
  File "/home/crodriguezde/experiments/reimage/imds.py", line 17, in _get
    instance_vm = _wait_vm_state_running(args, vmss_vm)
NameError: name 'args' is not defined
[ 2022-04-27T20:03:50    ERROR ] Task exception was never retrieved
future: <Task finished name='Task-9' coro=<_get() done, defined at /home/crodriguezde/experiments/reimage/imds.py:14> exception=NameError("name 'args' is not defined")>
Traceback (most recent call last):
  File "/home/crodriguezde/experiments/reimage/imds.py", line 17, in _get
    instance_vm = _wait_vm_state_running(args, vmss_vm)
NameError: name 'args' is not defined
[ 2022-04-27T20:03:50    ERROR ] Task exception was never retrieved
future: <Task finished name='Task-8' coro=<_get() done, defined at /home/crodriguezde/experiments/reimage/imds.py:14> exception=NameError("name 'args' is not defined")>
Traceback (most recent call last):
  File "/home/crodriguezde/experiments/reimage/imds.py", line 17, in _get
    instance_vm = _wait_vm_state_running(args, vmss_vm)
NameError: name 'args' is not defined
[ 2022-04-27T20:03:50    ERROR ] Task exception was never retrieved
future: <Task finished name='Task-7' coro=<_get() done, defined at /home/crodriguezde/experiments/reimage/imds.py:14> exception=NameError("name 'args' is not defined")>
Traceback (most recent call last):
  File "/home/crodriguezde/experiments/reimage/imds.py", line 17, in _get
    instance_vm = _wait_vm_state_running(args, vmss_vm)
NameError: name 'args' is not defined
[ 2022-04-27T20:03:50    ERROR ] Task exception was never retrieved
future: <Task finished name='Task-6' coro=<_get() done, defined at /home/crodriguezde/experiments/reimage/imds.py:14> exception=NameError("name 'args' is not defined")>
Traceback (most recent call last):
  File "/home/crodriguezde/experiments/reimage/imds.py", line 17, in _get
    instance_vm = _wait_vm_state_running(args, vmss_vm)
NameError: name 'args' is not defined
[ 2022-04-27T20:03:50    ERROR ] Task exception was never retrieved
future: <Task finished name='Task-5' coro=<_get() done, defined at /home/crodriguezde/experiments/reimage/imds.py:14> exception=NameError("name 'args' is not defined")>
Traceback (most recent call last):
  File "/home/crodriguezde/experiments/reimage/imds.py", line 17, in _get
    instance_vm = _wait_vm_state_running(args, vmss_vm)
NameError: name 'args' is not defined
[ 2022-04-27T20:03:50    ERROR ] Task exception was never retrieved
future: <Task finished name='Task-4' coro=<_get() done, defined at /home/crodriguezde/experiments/reimage/imds.py:14> exception=NameError("name 'args' is not defined")>
Traceback (most recent call last):
  File "/home/crodriguezde/experiments/reimage/imds.py", line 17, in _get
    instance_vm = _wait_vm_state_running(args, vmss_vm)
NameError: name 'args' is not defined
[ 2022-04-27T20:03:50    ERROR ] Task exception was never retrieved
future: <Task finished name='Task-3' coro=<_get() done, defined at /home/crodriguezde/experiments/reimage/imds.py:14> exception=NameError("name 'args' is not defined")>
Traceback (most recent call last):
  File "/home/crodriguezde/experiments/reimage/imds.py", line 17, in _get
    instance_vm = _wait_vm_state_running(args, vmss_vm)
NameError: name 'args' is not defined
[ 2022-04-27T20:03:50    ERROR ] Task exception was never retrieved
future: <Task finished name='Task-2' coro=<_get() done, defined at /home/crodriguezde/experiments/reimage/imds.py:14> exception=NameError("name 'args' is not defined")>
Traceback (most recent call last):
  File "/home/crodriguezde/experiments/reimage/imds.py", line 17, in _get
    instance_vm = _wait_vm_state_running(args, vmss_vm)
NameError: name 'args' is not defined
[ 2022-04-27T20:03:50    ERROR ] Task exception was never retrieved
future: <Task finished name='Task-11' coro=<_get() done, defined at /home/crodriguezde/experiments/reimage/imds.py:14> exception=NameError("name 'args' is not defined")>
Traceback (most recent call last):
  File "/home/crodriguezde/experiments/reimage/imds.py", line 17, in _get
    instance_vm = _wait_vm_state_running(args, vmss_vm)
NameError: name 'args' is not defined
[ 2022-04-27T20:03:50     INFO ] Exit per user request
